import { Kysely } from "kysely"
import { Database } from "../types/index.js"

export async function seed(db: Kysely<Database>): Promise<void> {
  const materials = [
    {
      id: 5254,
      name: "ADS 0.05 ml",
      description: "Auto disable/destruct syringe with needle 0,05ml 23G 1\" Steril Luer Lock (Umum)",
      material_level_id: 3,
      code: "ADS 0.05 ml",
      hierarchy_code: null,
      unit_of_consumption_id: 2,
      unit_of_distribution_id: 6,
      consumption_unit_per_distribution_unit: 1,
      is_temperature_sensitive: 0,
      min_retail_price: 0,
      max_retail_price: 0,
      min_temperature: 0,
      max_temperature: 0,
      material_type_id: 2,
      material_subtype_id: null,
      is_managed_in_batch: 1,
      status: 1,
      created_by: 121597,
      updated_by: 135292,
      deleted_by: null,
      is_stock_opname_mandatory: 0,
      is_kfa: 1,
    },
    {
      id: 5255,
      name: "ADS 0.3 ml",
      description: "Auto disable/destruct syringe with needle 0,3ml 23G 1\" Steril Luer Lock (Umum)",
      material_level_id: 3,
      code: "ADS 0.3 ml",
      hierarchy_code: null,
      unit_of_consumption_id: 2,
      unit_of_distribution_id: 6,
      consumption_unit_per_distribution_unit: 1,
      is_temperature_sensitive: 0,
      min_retail_price: 0,
      max_retail_price: 0,
      min_temperature: 0,
      max_temperature: 0,
      material_type_id: 2,
      material_subtype_id: null,
      is_managed_in_batch: 1,
      status: 1,
      created_by: 121597,
      updated_by: 135292,
      deleted_by: null,
      is_stock_opname_mandatory: 0,
      is_kfa: 1,
    },
    {
      id: 5256,
      name: "ADS 0.5 ml",
      description: "Auto disable/destruct syringe with needle 0,5ml 23G 1\" Steril Luer Lock (Umum)",
      material_level_id: 3,
      code: "ADS 0.5 ml",
      hierarchy_code: null,
      unit_of_consumption_id: 2,
      unit_of_distribution_id: 6,
      consumption_unit_per_distribution_unit: 1,
      is_temperature_sensitive: 0,
      min_retail_price: 0,
      max_retail_price: 0,
      min_temperature: 0,
      max_temperature: 0,
      material_type_id: 2,
      material_subtype_id: null,
      is_managed_in_batch: 1,
      status: 1,
      created_by: 121597,
      updated_by: 135292,
      deleted_by: null,
      is_stock_opname_mandatory: 0,
      is_kfa: 1,
    },
  ]

  for (const material of materials) {
    await db
      .insertInto("materials")
      .values(material)
      .onDuplicateKeyUpdate({
        name: material.name,
        description: material.description,
        material_level_id: material.material_level_id,
        code: material.code,
        unit_of_consumption_id: material.unit_of_consumption_id,
        unit_of_distribution_id: material.unit_of_distribution_id,
        consumption_unit_per_distribution_unit: material.consumption_unit_per_distribution_unit,
        is_temperature_sensitive: material.is_temperature_sensitive,
        min_retail_price: material.min_retail_price,
        max_retail_price: material.max_retail_price,
        material_type_id: material.material_type_id,
        is_managed_in_batch: material.is_managed_in_batch,
        status: material.status,
        updated_by: material.updated_by,
      })
      .execute()
  }
}
