/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type DeleteV2MasterActivityId200 = {
  message: string;
};

export type PutV2MasterActivityIdBody = {
  name: string;
  is_ordered_sales: number;
  is_ordered_purchase: number;
};

export type PutV2MasterActivityId200 = {
  id: number;
  name: string;
  code: null;
  is_ordered_sales: number;
  is_ordered_purchase: number;
  created_by: number;
  updated_by: number;
  deleted_by: null;
  is_patient_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
};

export type PostV2MasterActivityBody = {
  name: string;
  is_ordered_sales: number;
  is_ordered_purchase: number;
};

export type PostV2MasterActivity201 = {
  id: number;
  name: string;
  code: null;
  is_ordered_sales: number;
  is_ordered_purchase: number;
  created_by: number;
  updated_by: number;
  deleted_by: null;
  is_patient_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
};

export const getSmile = () => {
/**
 * @summary v2/master-activity/:id
 */
const deleteV2MasterActivityId = <TData = AxiosResponse<DeleteV2MasterActivityId200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/master-activity/${id}`,options
    );
  }

/**
 * @summary v2/master-activity/:id
 */
const putV2MasterActivityId = <TData = AxiosResponse<PutV2MasterActivityId200>>(
    id: number,
    putV2MasterActivityIdBody: PutV2MasterActivityIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/master-activity/${id}`,
      putV2MasterActivityIdBody,options
    );
  }

/**
 * @summary v2/master-activity
 */
const postV2MasterActivity = <TData = AxiosResponse<PostV2MasterActivity201>>(
    postV2MasterActivityBody: PostV2MasterActivityBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/master-activity`,
      postV2MasterActivityBody,options
    );
  }

return {deleteV2MasterActivityId,putV2MasterActivityId,postV2MasterActivity}};
export type DeleteV2MasterActivityIdResult = AxiosResponse<DeleteV2MasterActivityId200>
export type PutV2MasterActivityIdResult = AxiosResponse<PutV2MasterActivityId200>
export type PostV2MasterActivityResult = AxiosResponse<PostV2MasterActivity201>
