/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostSourceAssetBody = {
  name: string;
  description: string;
};

export type PostSourceAsset200 = {
  id: number;
  name: string;
  description: string;
  created_by: number;
  updated_by: number;
  updated_at: string;
  created_at: string;
};

export type DeleteSourceAssetBody = {
  id: string;
};

export type DeleteSourceAsset200 = {
  message: string;
};

export type PutSourceAssetIdBody = {
  name: string;
  description: string;
};

export type PutSourceAssetId200 = {
  id: number;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  created_by: number;
  updated_by: number;
  deleted_by: null;
};

export const getSmile = () => {
/**
 * @summary /source-asset
 */
const postSourceAsset = <TData = AxiosResponse<PostSourceAsset200>>(
    postSourceAssetBody: PostSourceAssetBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/source-asset`,
      postSourceAssetBody,options
    );
  }

/**
 * @summary /source-asset
 */
const deleteSourceAsset = <TData = AxiosResponse<DeleteSourceAsset200>>(
    deleteSourceAssetBody: DeleteSourceAssetBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append('id', deleteSourceAssetBody.id)

    return axios.delete(
      `/source-asset`,{data:
      formUrlEncoded, ...options}
    );
  }

/**
 * @summary /source-asset/{id}
 */
const putSourceAssetId = <TData = AxiosResponse<PutSourceAssetId200>>(
    id: number,
    putSourceAssetIdBody: PutSourceAssetIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/source-asset/${id}`,
      putSourceAssetIdBody,options
    );
  }

return {postSourceAsset,deleteSourceAsset,putSourceAssetId}};
export type PostSourceAssetResult = AxiosResponse<PostSourceAsset200>
export type DeleteSourceAssetResult = AxiosResponse<DeleteSourceAsset200>
export type PutSourceAssetIdResult = AxiosResponse<PutSourceAssetId200>
