/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type GetV2OrderId200 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * @summary Order Detail
 */
const getV2OrderId = <TData = AxiosResponse<GetV2OrderId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v2/order/${id}`,options
    );
  }

return {getV2OrderId}};
export type GetV2OrderIdResult = AxiosResponse<GetV2OrderId200>
