/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutV2MaterialEntityIdBody = {
  id: number;
  entity_master_material_id: number;
  activity_id: number;
  min: number;
  max: number;
  consumption_rate: number;
  retailer_price: number;
  tax: number;
};

export type PutV2MaterialEntityId200 = {
  message: string;
};

export type DeleteV2MaterialEntityId200 = { [key: string]: unknown };

export type PostV2MaterialEntityBody = {
  master_material_id: number;
  entity_id: number;
  activity_id: number;
  min: number;
  max: number;
  consumption_rate: number;
  retailer_price: number;
  tax: number;
};

export type PostV2MaterialEntity201Item = {
  available: null;
  id: number;
  entity_master_material_id: number;
  activity_id: number;
  min: number;
  max: number;
  consumption_rate: number;
  retailer_price: number;
  tax: number;
  created_by: number;
  updated_by: number;
  updated_at: string;
  created_at: string;
};

export const getSmile = () => {
/**
 * @summary /v2/material-entity/:id
 */
const putV2MaterialEntityId = <TData = AxiosResponse<PutV2MaterialEntityId200>>(
    id: string,
    putV2MaterialEntityIdBody: PutV2MaterialEntityIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/material-entity/${id}`,
      putV2MaterialEntityIdBody,options
    );
  }

/**
 * @summary /v2/material-entity/:id
 */
const deleteV2MaterialEntityId = <TData = AxiosResponse<DeleteV2MaterialEntityId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/material-entity/${id}`,options
    );
  }

/**
 * @summary /v2/material-entity
 */
const postV2MaterialEntity = <TData = AxiosResponse<PostV2MaterialEntity201Item[]>>(
    postV2MaterialEntityBody: PostV2MaterialEntityBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/material-entity`,
      postV2MaterialEntityBody,options
    );
  }

return {putV2MaterialEntityId,deleteV2MaterialEntityId,postV2MaterialEntity}};
export type PutV2MaterialEntityIdResult = AxiosResponse<PutV2MaterialEntityId200>
export type DeleteV2MaterialEntityIdResult = AxiosResponse<DeleteV2MaterialEntityId200>
export type PostV2MaterialEntityResult = AxiosResponse<PostV2MaterialEntity201Item[]>
