/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutEntityIdCustomersBody = {
  customer_id: number[];
  is_consumption: number;
};

export type PutEntityIdCustomers401 = {
  message: string;
};

export type PutEntityIdCustomers500 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * This function comment is parsed by doctrine
 * @summary /entity/:id/customers Copy
 */
const putEntityIdCustomers = <TData = AxiosResponse<unknown>>(
    id: string,
    putEntityIdCustomersBody: PutEntityIdCustomersBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/entity/${id}/customers`,
      putEntityIdCustomersBody,options
    );
  }

return {putEntityIdCustomers}};
export type PutEntityIdCustomersResult = AxiosResponse<unknown>
