/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostManufactureBody = {
  reference_id: string;
  name: string;
  contact_name?: string;
  description?: string;
  email?: string;
  phone_number?: string;
  address?: string;
  is_asset: number;
  status: number;
  type: number;
};

export type PostManufacture201UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PostManufacture201UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PostManufacture201 = {
  id: number;
  name: string;
  reference_id: string;
  description: string;
  contact_name: string;
  phone_number: string;
  email: string;
  address: string;
  status: number;
  type: number;
  is_asset: number;
  updated_at: string;
  updated_by: number;
  user_created_by: PostManufacture201UserCreatedBy;
  user_updated_by: PostManufacture201UserUpdatedBy;
  user_deleted_by: null;
};

export type PostManufacture500 = { [key: string]: unknown };

export type PutManufactureIdBody = {
  reference_id: string;
  name: string;
  contact_name?: string;
  description?: string;
  email?: string;
  phone_number?: string;
  address?: string;
  is_asset: number;
  status: number;
  type: number;
};

export type PutManufactureId200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutManufactureId200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutManufactureId200 = {
  id: number;
  name: string;
  reference_id: string;
  description: string;
  contact_name: string;
  phone_number: string;
  email: string;
  address: string;
  status: number;
  type: number;
  is_asset: number;
  updated_at: string;
  updated_by: number;
  user_created_by: PutManufactureId200UserCreatedBy;
  user_updated_by: PutManufactureId200UserUpdatedBy;
  user_deleted_by: null;
};

export type PutManufactureId404 = { [key: string]: unknown };

export type PutManufactureId500 = { [key: string]: unknown };

export type DeleteManufactureId200 = {
  message: string;
};

export type DeleteManufactureId404 = { [key: string]: unknown };

export type DeleteManufactureId500 = { [key: string]: unknown };

export type PutManufactureIdStatusBody = {
  status: number;
};

export type PutManufactureIdStatus200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutManufactureIdStatus200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutManufactureIdStatus200 = {
  id: number;
  name: string;
  reference_id: string;
  description: string;
  contact_name: string;
  phone_number: string;
  email: string;
  address: string;
  status: number;
  type: number;
  is_asset: number;
  updated_at: string;
  updated_by: number;
  user_created_by: PutManufactureIdStatus200UserCreatedBy;
  user_updated_by: PutManufactureIdStatus200UserUpdatedBy;
  user_deleted_by: null;
};

export type PutManufactureIdStatus404 = { [key: string]: unknown };

export type PutManufactureIdStatus500 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * This function comment is parsed by doctrine
 * @summary /manufacture
 */
const postManufacture = <TData = AxiosResponse<PostManufacture201>>(
    postManufactureBody: PostManufactureBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/manufacture`,
      postManufactureBody,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /manufacture/:id
 */
const putManufactureId = <TData = AxiosResponse<PutManufactureId200>>(
    id: string,
    putManufactureIdBody: PutManufactureIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/manufacture/${id}`,
      putManufactureIdBody,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /manufacture/:id
 */
const deleteManufactureId = <TData = AxiosResponse<DeleteManufactureId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/manufacture/${id}`,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /manufacture/:id/status
 */
const putManufactureIdStatus = <TData = AxiosResponse<PutManufactureIdStatus200>>(
    id: string,
    putManufactureIdStatusBody: PutManufactureIdStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/manufacture/${id}/status`,
      putManufactureIdStatusBody,options
    );
  }

return {postManufacture,putManufactureId,deleteManufactureId,putManufactureIdStatus}};
export type PostManufactureResult = AxiosResponse<PostManufacture201>
export type PutManufactureIdResult = AxiosResponse<PutManufactureId200>
export type DeleteManufactureIdResult = AxiosResponse<DeleteManufactureId200>
export type PutManufactureIdStatusResult = AxiosResponse<PutManufactureIdStatus200>
