/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type DeleteV2MaterialId200 = {
  message: string;
};

export type PutV2MaterialIdBodyAddremove = {
  entity_types: string[];
  roles: string[];
};

export type PutV2MaterialIdBody = {
  name: string;
  description: string;
  code: string;
  code_kfa: null;
  unit: string;
  pieces_per_unit: number;
  temperature_sensitive: number;
  temperature_min: number;
  temperature_max: number;
  managed_in_batch: number;
  activities: number[];
  manufactures: number[];
  material_companion: number[];
  addremove: PutV2MaterialIdBodyAddremove;
  kfa_level_id: number;
  unit_of_distribution: string;
  min_retail_price: number;
  max_retail_price: number;
  status: number;
};

export type PutV2MaterialId200 = {
  material_companion_label: string;
  manufactures_label: string;
  material_activities_label: string;
  user_updated_by_label: string;
  status_label: string;
  kfa_level_label: string;
  parent_label: string;
  parent_kfa_code_label: string;
  id: number;
  name: string;
  unit_of_distribution: string;
  code: string;
  description: string;
  pieces_per_unit: number;
  unit: string;
  temperature_sensitive: number;
  temperature_min: number;
  temperature_max: number;
  created_by: number;
  updated_by: number;
  deleted_by: null;
  managed_in_batch: number;
  status: number;
  is_vaccine: number;
  is_stockcount: number;
  is_addremove: number;
  is_openvial: number;
  kfa_code: null;
  need_sequence: null;
  range_temperature_id: null;
  kfa_level_id: number;
  parent_id: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
};

export type PostV2MaterialBodyAddremove = {
  entity_types: number[];
  roles: number[];
};

export type PostV2MaterialBodyKfa = {
  id: number;
  code: number;
};

export type PostV2MaterialBody = {
  name: string;
  description: string;
  code: string;
  unit: string;
  pieces_per_unit: string;
  temperature_sensitive: number;
  temperature_min: string;
  temperature_max: string;
  managed_in_batch: number;
  activities: number[];
  manufactures: number[];
  material_companion: number[];
  is_vaccine: number;
  is_addremove: number;
  addremove: PostV2MaterialBodyAddremove;
  status: number;
  need_sequence: number;
  unit_of_distribution: string;
  material_activities: number;
  parent_id?: number;
  kfa?: PostV2MaterialBodyKfa;
};

export type PostV2Material201Addremove = {
  roles: number[];
  entity_types: number[];
};

export type PostV2Material201 = {
  material_companion_label: string;
  manufactures_label: string;
  material_activities_label: string;
  user_updated_by_label: string;
  status_label: string;
  kfa_level_label: string;
  parent_label: string;
  parent_kfa_code_label: string;
  id: number;
  name: string;
  unit_of_distribution: string;
  code: string;
  description: string;
  pieces_per_unit: number;
  unit: string;
  temperature_sensitive: number;
  temperature_min: number;
  temperature_max: number;
  created_by: number;
  updated_by: number;
  deleted_by: null;
  managed_in_batch: number;
  status: number;
  is_vaccine: number;
  is_stockcount: number;
  is_addremove: number;
  is_openvial: number;
  kfa_code: null;
  need_sequence: number;
  range_temperature_id: null;
  kfa_level_id: null;
  parent_id: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  addremove: PostV2Material201Addremove;
};

export type PutV2MaterialIdStatusBody = {
  status: number;
};

export type PutV2MaterialIdStatus200 = {
  message: string;
};

export const getSmile = () => {
/**
 * @summary v2/material/{id}
 */
const deleteV2MaterialId = <TData = AxiosResponse<DeleteV2MaterialId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/material/${id}`,options
    );
  }

/**
 * @summary v2/material/{id}
 */
const putV2MaterialId = <TData = AxiosResponse<PutV2MaterialId200>>(
    id: string,
    putV2MaterialIdBody: PutV2MaterialIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/material/${id}`,
      putV2MaterialIdBody,options
    );
  }

/**
 * @summary v2/material
 */
const postV2Material = <TData = AxiosResponse<PostV2Material201>>(
    postV2MaterialBody: PostV2MaterialBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/material`,
      postV2MaterialBody,options
    );
  }

/**
 * @summary v2/material/{id}/status
 */
const putV2MaterialIdStatus = <TData = AxiosResponse<PutV2MaterialIdStatus200>>(
    id: string,
    putV2MaterialIdStatusBody: PutV2MaterialIdStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/material/${id}/status`,
      putV2MaterialIdStatusBody,options
    );
  }

return {deleteV2MaterialId,putV2MaterialId,postV2Material,putV2MaterialIdStatus}};
export type DeleteV2MaterialIdResult = AxiosResponse<DeleteV2MaterialId200>
export type PutV2MaterialIdResult = AxiosResponse<PutV2MaterialId200>
export type PostV2MaterialResult = AxiosResponse<PostV2Material201>
export type PutV2MaterialIdStatusResult = AxiosResponse<PutV2MaterialIdStatus200>
