/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutV2OrderIdAllocateBodyItem = {
  /** @nullable */
  status: number | null;
  order_item_id: number;
  allocated_stock_id: number;
  allocated_qty: number;
};

export type PutV2OrderIdAllocate200OrderItemsItemMasterMaterial = {
  id: number;
  code: string;
  name: string;
};

export type PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStockBatchManufacture = {
  id: number;
  name: string;
};

export type PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStockBatch = {
  manufacture_name: string;
  id: number;
  manufacture_id: number;
  code: string;
  expired_date: string;
  production_date: string;
  manufacture: PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStockBatchManufacture;
};

export type PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStock = {
  id: number;
  batch_id: number;
  qty: number;
  batch: PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStockBatch;
};

export type PutV2OrderIdAllocate200OrderItemsItemOrderStocksItem = {
  id: number;
  status?: null;
  order_item_id: number;
  stock_id: number;
  allocated_qty?: number;
  received_qty?: null;
  ordered_qty?: null;
  qrcode?: null;
  stock?: PutV2OrderIdAllocate200OrderItemsItemOrderStocksItemStock;
  order_stock_purchase?: null;
};

export type PutV2OrderIdAllocate200OrderItemsItem = {
  id?: number;
  qty?: number;
  material_id?: null;
  recommended_stock?: number;
  material?: null;
  master_material?: PutV2OrderIdAllocate200OrderItemsItemMasterMaterial;
  order_stocks?: PutV2OrderIdAllocate200OrderItemsItemOrderStocksItem[];
};

export type PutV2OrderIdAllocate200OrderCommentsItemUser = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdAllocate200OrderCommentsItem = {
  id: number;
  comment: string;
  created_at: string;
  order_status: number;
  user: PutV2OrderIdAllocate200OrderCommentsItemUser;
};

export type PutV2OrderIdAllocate200Customer = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: null;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: null;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PutV2OrderIdAllocate200Vendor = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: null;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: null;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: null;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PutV2OrderIdAllocate200UserConfirmedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdAllocate200UserAllocatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutV2OrderIdAllocate200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdAllocate200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutV2OrderIdAllocate200 = {
  status_label: string;
  id: number;
  device_type: null;
  customer_id: number;
  vendor_id: number;
  status: number;
  type: number;
  required_date: string;
  estimated_date: null;
  actual_shipment: null;
  purchase_ref: null;
  sales_ref: null;
  reason: null;
  cancel_reason: null;
  delivery_number: null;
  confirmed_at: string;
  shipped_at: null;
  fulfilled_at: null;
  cancelled_at: null;
  allocated_at: string;
  created_at: string;
  updated_at: string;
  is_allocated: number;
  taken_by_customer: number;
  other_reason: null;
  is_kpcpen: null;
  qty_kpcpen: null;
  master_order_id: null;
  easygo_no_do: null;
  biofarma_changed: null;
  service_type: null;
  no_document: null;
  released_date: null;
  notes: null;
  activity_id: number;
  is_manual: null;
  no_po: null;
  created_by: number;
  validated_by: null;
  validated_at: null;
  order_tags: string[];
  order_items: PutV2OrderIdAllocate200OrderItemsItem[];
  order_comments: PutV2OrderIdAllocate200OrderCommentsItem[];
  customer: PutV2OrderIdAllocate200Customer;
  vendor: PutV2OrderIdAllocate200Vendor;
  user_confirmed_by: PutV2OrderIdAllocate200UserConfirmedBy;
  user_shipped_by: null;
  user_fulfilled_by: null;
  user_cancelled_by: null;
  user_allocated_by: PutV2OrderIdAllocate200UserAllocatedBy;
  user_created_by: PutV2OrderIdAllocate200UserCreatedBy;
  user_updated_by: PutV2OrderIdAllocate200UserUpdatedBy;
  user_deleted_by: null;
  user_validated_by: null;
};

export const getSmile = () => {
/**
 * @summary /v2/order/:id/allocate
 */
const putV2OrderIdAllocate = <TData = AxiosResponse<PutV2OrderIdAllocate200>>(
    id: number,
    putV2OrderIdAllocateBodyItem: PutV2OrderIdAllocateBodyItem[], options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/order/${id}/allocate`,
      putV2OrderIdAllocateBodyItem,options
    );
  }

return {putV2OrderIdAllocate}};
export type PutV2OrderIdAllocateResult = AxiosResponse<PutV2OrderIdAllocate200>
