/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutV2OrderIdShipBody = {
  comment: string;
  estimated_date: string;
  taken_by_customer: number;
  sales_ref: string;
};

export type PutV2OrderIdShip200 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * @summary Mengirimkan Pesanan
 */
const putV2OrderIdShip = <TData = AxiosResponse<PutV2OrderIdShip200>>(
    id: string,
    putV2OrderIdShipBody: PutV2OrderIdShipBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/order/${id}/ship`,
      putV2OrderIdShipBody,options
    );
  }

return {putV2OrderIdShip}};
export type PutV2OrderIdShipResult = AxiosResponse<PutV2OrderIdShip200>
