/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutOrderIdCancelBody = {
  cancel_reason: string;
  reason_text?: string;
  comment: string;
};

export type PutOrderIdCancel200Activity = {
  id: number;
  name: string;
};

export type PutOrderIdCancel200OrderItemsItemMasterMaterial = {
  id: number;
  code: string;
  name: string;
};

export type PutOrderIdCancel200OrderItemsItemOrderStocksItemStockBatchManufacture = {
  id: number;
  name: string;
};

export type PutOrderIdCancel200OrderItemsItemOrderStocksItemStockBatch = {
  manufacture_name: string;
  id: number;
  manufacture_id: number;
  code: string;
  expired_date: string;
  production_date: string;
  manufacture: PutOrderIdCancel200OrderItemsItemOrderStocksItemStockBatchManufacture;
};

export type PutOrderIdCancel200OrderItemsItemOrderStocksItemStock = {
  id: number;
  batch_id: number;
  qty: number;
  batch: PutOrderIdCancel200OrderItemsItemOrderStocksItemStockBatch;
};

export type PutOrderIdCancel200OrderItemsItemOrderStocksItem = {
  id: number;
  status: null;
  order_item_id: number;
  stock_id: number;
  allocated_qty: number;
  received_qty: null;
  ordered_qty: null;
  qrcode: null;
  stock: PutOrderIdCancel200OrderItemsItemOrderStocksItemStock;
  order_stock_purchase: null;
};

export type PutOrderIdCancel200OrderItemsItem = {
  id: number;
  qty: number;
  material_id: null;
  /** @nullable */
  recommended_stock: number | null;
  material: null;
  master_material: PutOrderIdCancel200OrderItemsItemMasterMaterial;
  order_stocks: PutOrderIdCancel200OrderItemsItemOrderStocksItem[];
};

export type PutOrderIdCancel200OrderCommentsItemUser = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutOrderIdCancel200OrderCommentsItem = {
  id?: number;
  comment?: string;
  created_at?: string;
  order_status?: number;
  user?: PutOrderIdCancel200OrderCommentsItemUser;
};

export type PutOrderIdCancel200Customer = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: string;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PutOrderIdCancel200VendorMappingEntity = {
  id: number;
  id_entitas_smile: number;
  id_pusdatin: null;
  id_bpjs: null;
  id_satu_sehat: number;
};

export type PutOrderIdCancel200Vendor = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: PutOrderIdCancel200VendorMappingEntity;
};

export type PutOrderIdCancel200UserConfirmedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutOrderIdCancel200UserCancelledBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutOrderIdCancel200UserAllocatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: null;
};

export type PutOrderIdCancel200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutOrderIdCancel200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutOrderIdCancel200 = {
  status_label: string;
  id: number;
  device_type: number;
  customer_id: number;
  vendor_id: number;
  status: number;
  type: number;
  required_date: null;
  estimated_date: null;
  actual_shipment: null;
  purchase_ref: null;
  sales_ref: null;
  reason: null;
  cancel_reason: number;
  delivery_number: null;
  confirmed_at: string;
  shipped_at: null;
  fulfilled_at: null;
  cancelled_at: string;
  allocated_at: string;
  created_at: string;
  updated_at: string;
  is_allocated: number;
  taken_by_customer: number;
  other_reason: null;
  is_kpcpen: null;
  qty_kpcpen: null;
  master_order_id: null;
  easygo_no_do: null;
  biofarma_changed: null;
  service_type: null;
  no_document: null;
  released_date: null;
  notes: null;
  activity_id: number;
  is_manual: null;
  no_po: null;
  created_by: number;
  validated_by: null;
  validated_at: null;
  activity: PutOrderIdCancel200Activity;
  order_tags: string[];
  order_items: PutOrderIdCancel200OrderItemsItem[];
  order_comments: PutOrderIdCancel200OrderCommentsItem[];
  customer: PutOrderIdCancel200Customer;
  vendor: PutOrderIdCancel200Vendor;
  user_confirmed_by: PutOrderIdCancel200UserConfirmedBy;
  user_shipped_by: null;
  user_fulfilled_by: null;
  user_cancelled_by: PutOrderIdCancel200UserCancelledBy;
  user_allocated_by: PutOrderIdCancel200UserAllocatedBy;
  user_created_by: PutOrderIdCancel200UserCreatedBy;
  user_updated_by: PutOrderIdCancel200UserUpdatedBy;
  user_deleted_by: null;
  user_validated_by: null;
};

export type PutOrderIdCancel500 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * This function comment is parsed by doctrine
 * @summary /order/:id/cancel
 */
const putOrderIdCancel = <TData = AxiosResponse<PutOrderIdCancel200>>(
    id: string,
    putOrderIdCancelBody: PutOrderIdCancelBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/order/${id}/cancel`,
      putOrderIdCancelBody,options
    );
  }

return {putOrderIdCancel}};
export type PutOrderIdCancelResult = AxiosResponse<PutOrderIdCancel200>
