/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * @nullable
 */
export type PostV2OrderBodyOrderComment = {
  /** @nullable */
  comment?: string | null;
} | null;

export type PostV2OrderBodyOrderItemsItem = {
  ordered_qty: number;
  material_id: number;
  /** @nullable */
  reason_id?: number | null;
  /** @nullable */
  recommended_stock?: number | null;
  /** @nullable */
  other_reason?: string | null;
};

export type PostV2OrderBody = {
  type: number;
  customer_id: number;
  vendor_id: number;
  /** @nullable */
  required_date?: string | null;
  activity_id: number;
  status: number;
  /** @nullable */
  order_comment?: PostV2OrderBodyOrderComment;
  order_items: PostV2OrderBodyOrderItemsItem[];
};

export type PostV2Order200OrderItemProjectionCapacitiesItem = {
  capacity_asset?: number;
  total_volume?: number;
  percent_capacity?: number;
  is_confirm?: boolean;
};

export type PostV2Order200OrderItemsItemMasterMaterial = {
  id: number;
  code: string;
  name: string;
};

export type PostV2Order200OrderItemsItem = {
  id?: number;
  qty?: number;
  material_id?: null;
  recommended_stock?: number;
  material?: null;
  master_material: PostV2Order200OrderItemsItemMasterMaterial;
  order_stocks?: string[];
};

export type PostV2Order200OrderCommentsItemUser = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2Order200OrderCommentsItem = {
  id?: number;
  comment?: string;
  created_at?: string;
  order_status?: number;
  user?: PostV2Order200OrderCommentsItemUser;
};

export type PostV2Order200Customer = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: string;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PostV2Order200VendorMappingEntity = {
  id: number;
  id_entitas_smile: number;
  id_pusdatin: null;
  id_bpjs: null;
  id_satu_sehat: number;
};

export type PostV2Order200Vendor = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: PostV2Order200VendorMappingEntity;
};

export type PostV2Order200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2Order200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2Order200 = {
  status_label: string;
  id: number;
  device_type: null;
  customer_id: number;
  vendor_id: number;
  status: number;
  type: number;
  required_date: string;
  estimated_date: null;
  actual_shipment: null;
  purchase_ref: null;
  sales_ref: null;
  reason: null;
  cancel_reason: null;
  delivery_number: null;
  confirmed_at: null;
  shipped_at: null;
  fulfilled_at: null;
  cancelled_at: null;
  allocated_at: null;
  created_at: string;
  updated_at: string;
  is_allocated: number;
  taken_by_customer: number;
  other_reason: null;
  is_kpcpen: null;
  qty_kpcpen: null;
  master_order_id: null;
  easygo_no_do: null;
  biofarma_changed: null;
  service_type: null;
  no_document: null;
  released_date: null;
  notes: null;
  activity_id: number;
  is_manual: null;
  no_po: null;
  created_by: number;
  validated_by: null;
  validated_at: null;
  order_tags: string[];
  order_item_projection_capacities: PostV2Order200OrderItemProjectionCapacitiesItem[];
  order_items: PostV2Order200OrderItemsItem[];
  order_comments: PostV2Order200OrderCommentsItem[];
  customer: PostV2Order200Customer;
  vendor: PostV2Order200Vendor;
  user_confirmed_by: null;
  user_shipped_by: null;
  user_fulfilled_by: null;
  user_cancelled_by: null;
  user_allocated_by: null;
  user_created_by: PostV2Order200UserCreatedBy;
  user_updated_by: PostV2Order200UserUpdatedBy;
  user_deleted_by: null;
  user_validated_by: null;
};

export const getSmile = () => {
/**
 * @summary v2/order
 */
const postV2Order = <TData = AxiosResponse<PostV2Order200>>(
    postV2OrderBody: PostV2OrderBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/order`,
      postV2OrderBody,options
    );
  }

return {postV2Order}};
export type PostV2OrderResult = AxiosResponse<PostV2Order200>
