/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * @nullable
 */
export type PostV2OrderDroppingBodyOrderComment = {
  /** @nullable */
  comment?: string | null;
} | null;

export type PostV2OrderDroppingBodyOrderItemsItemBatchesItem = {
  activity_id: number;
  code: string;
  expired_date: string;
  production_date: string;
  manufacture_name: string;
  qty: number;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  source_material_id?: number | null;
  /** @nullable */
  total_price?: number | null;
  /** @nullable */
  year?: string | null;
};

export type PostV2OrderDroppingBodyOrderItemsItemStocksItem = {
  id?: number;
  qty?: number;
  activity_id?: number;
};

export type PostV2OrderDroppingBodyOrderItemsItem = {
  material_code: string;
  batches?: PostV2OrderDroppingBodyOrderItemsItemBatchesItem[];
  stocks?: PostV2OrderDroppingBodyOrderItemsItemStocksItem[];
};

export type PostV2OrderDroppingBody = {
  type: number;
  /** @nullable */
  required_date?: string | null;
  activity_id: number;
  /** @nullable */
  order_comment?: PostV2OrderDroppingBodyOrderComment;
  order_items: PostV2OrderDroppingBodyOrderItemsItem[];
  is_allocated: number;
  /** @nullable */
  is_manual?: number | null;
  vendor_code: string;
  customer_code: string;
  /** @nullable */
  delivery_number?: string | null;
  /** @nullable */
  no_po?: string | null;
  /** @nullable */
  service_type?: number | null;
};

export type PostV2OrderDropping201OrderItemsItemMasterMaterial = {
  id: number;
  code: string;
  name: string;
};

export type PostV2OrderDropping201OrderItemsItemOrderStocksItemStockBatchManufacture = {
  id: number;
  name: string;
};

export type PostV2OrderDropping201OrderItemsItemOrderStocksItemStockBatch = {
  manufacture_name: string;
  id: number;
  manufacture_id: number;
  code: string;
  expired_date: string;
  /** @nullable */
  production_date: string | null;
  manufacture: PostV2OrderDropping201OrderItemsItemOrderStocksItemStockBatchManufacture;
};

export type PostV2OrderDropping201OrderItemsItemOrderStocksItemStock = {
  id: number;
  batch_id: number;
  qty: number;
  batch: PostV2OrderDropping201OrderItemsItemOrderStocksItemStockBatch;
};

export type PostV2OrderDropping201OrderItemsItemOrderStocksItem = {
  id: number;
  status: null;
  order_item_id: number;
  stock_id: number;
  allocated_qty: number;
  received_qty: null;
  ordered_qty: number;
  qrcode: null;
  stock: PostV2OrderDropping201OrderItemsItemOrderStocksItemStock;
  order_stock_purchase: null;
};

export type PostV2OrderDropping201OrderItemsItem = {
  id?: number;
  qty?: number;
  material_id?: null;
  recommended_stock?: null;
  material?: null;
  master_material: PostV2OrderDropping201OrderItemsItemMasterMaterial;
  order_stocks?: PostV2OrderDropping201OrderItemsItemOrderStocksItem[];
};

export type PostV2OrderDropping201OrderCommentsItem = {
  id?: number;
  comment?: string;
};

export type PostV2OrderDropping201Customer = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: string;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PostV2OrderDropping201VendorMappingEntity = {
  id: number;
  id_entitas_smile: number;
  id_pusdatin: null;
  id_bpjs: null;
  id_satu_sehat: number;
};

export type PostV2OrderDropping201Vendor = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: string;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: string;
  is_ayosehat: number;
  mapping_entity: PostV2OrderDropping201VendorMappingEntity;
};

export type PostV2OrderDropping201UserConfirmedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2OrderDropping201UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2OrderDropping201UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PostV2OrderDropping201Activity = {
  id: number;
  name: string;
};

export type PostV2OrderDropping201 = {
  status_label: string;
  id: number;
  device_type: null;
  customer_id: number;
  vendor_id: number;
  status: number;
  type: number;
  required_date: string;
  estimated_date: null;
  actual_shipment: null;
  purchase_ref: null;
  sales_ref: null;
  reason: null;
  cancel_reason: null;
  delivery_number: null;
  confirmed_at: string;
  shipped_at: null;
  fulfilled_at: null;
  cancelled_at: null;
  allocated_at: null;
  created_at: string;
  updated_at: string;
  is_allocated: number;
  taken_by_customer: number;
  other_reason: null;
  is_kpcpen: null;
  qty_kpcpen: null;
  master_order_id: null;
  easygo_no_do: null;
  biofarma_changed: null;
  service_type: null;
  no_document: null;
  released_date: null;
  notes: null;
  activity_id: number;
  is_manual: null;
  no_po: null;
  created_by: number;
  validated_by: null;
  validated_at: null;
  order_tags: string[];
  order_items: PostV2OrderDropping201OrderItemsItem[];
  order_comments: PostV2OrderDropping201OrderCommentsItem[];
  customer: PostV2OrderDropping201Customer;
  vendor: PostV2OrderDropping201Vendor;
  user_confirmed_by: PostV2OrderDropping201UserConfirmedBy;
  user_shipped_by: null;
  user_fulfilled_by: null;
  user_cancelled_by: null;
  user_allocated_by: null;
  user_created_by: PostV2OrderDropping201UserCreatedBy;
  user_updated_by: PostV2OrderDropping201UserUpdatedBy;
  user_deleted_by: null;
  user_validated_by: null;
  activity: PostV2OrderDropping201Activity;
};

export const getSmile = () => {
/**
 * @summary v2/order/dropping
 */
const postV2OrderDropping = <TData = AxiosResponse<PostV2OrderDropping201>>(
    postV2OrderDroppingBody: PostV2OrderDroppingBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/order/dropping`,
      postV2OrderDroppingBody,options
    );
  }

return {postV2OrderDropping}};
export type PostV2OrderDroppingResult = AxiosResponse<PostV2OrderDropping201>
