/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PutV2OrderIdFulfilledBodyOrderItemsItemOrderStockFulfillItem = {
  order_stock_ids: number[];
  /** @nullable */
  batch_id: number | null;
  /** @nullable */
  status: number | null;
  fulfill_reason: null;
  other_reason: null;
  /** @nullable */
  qrcode: string | null;
  received_qty: number;
};

export type PutV2OrderIdFulfilledBodyOrderItemsItem = {
  id: number;
  material_id: number;
  order_stock_fulfill: PutV2OrderIdFulfilledBodyOrderItemsItemOrderStockFulfillItem[];
};

export type PutV2OrderIdFulfilledBody = {
  comment: string;
  fulfilled_at: string;
  order_items: PutV2OrderIdFulfilledBodyOrderItemsItem[];
};

export type PutV2OrderIdFulfilled200Activity = {
  id: number;
  name: string;
};

export type PutV2OrderIdFulfilled200OrderItemsItemMasterMaterial = {
  id: number;
  code: string;
  name: string;
};

export type PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStockBatchManufacture = {
  id: number;
  name: string;
};

export type PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStockBatch = {
  manufacture_name: string;
  id: number;
  manufacture_id: number;
  code: string;
  expired_date: string;
  production_date: string;
  manufacture: PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStockBatchManufacture;
};

export type PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStock = {
  id: number;
  batch_id: number;
  qty: number;
  batch: PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStockBatch;
};

export type PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItem = {
  id?: number;
  status?: null;
  order_item_id?: number;
  stock_id?: number;
  allocated_qty?: number;
  received_qty?: number;
  ordered_qty?: number;
  qrcode?: null;
  stock?: PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItemStock;
  order_stock_purchase?: null;
};

export type PutV2OrderIdFulfilled200OrderItemsItem = {
  id?: number;
  qty?: number;
  material_id?: null;
  recommended_stock?: null;
  material?: null;
  master_material?: PutV2OrderIdFulfilled200OrderItemsItemMasterMaterial;
  order_stocks?: PutV2OrderIdFulfilled200OrderItemsItemOrderStocksItem[];
};

export type PutV2OrderIdFulfilled200OrderCommentsItemUser = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200OrderCommentsItem = {
  id?: number;
  comment?: null;
  created_at?: string;
  order_status?: number;
  user?: PutV2OrderIdFulfilled200OrderCommentsItemUser;
};

export type PutV2OrderIdFulfilled200Customer = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: string;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: null;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: null;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PutV2OrderIdFulfilled200Vendor = {
  type_label: string;
  id: number;
  name: string;
  address: string;
  code: string;
  type: number;
  status: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  province_id: string;
  regency_id: null;
  village_id: null;
  sub_district_id: null;
  lat: null;
  lng: null;
  postal_code: null;
  is_vendor: number;
  bpom_key: null;
  is_puskesmas: number;
  rutin_join_date: null;
  is_ayosehat: number;
  mapping_entity: null;
};

export type PutV2OrderIdFulfilled200UserConfirmedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200UserShippedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200UserFulfilledBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200UserAllocatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200UserCreatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200UserUpdatedBy = {
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
};

export type PutV2OrderIdFulfilled200 = {
  status_label: string;
  id: number;
  device_type: null;
  customer_id: number;
  vendor_id: number;
  status: number;
  type: number;
  required_date: string;
  estimated_date: null;
  actual_shipment: null;
  purchase_ref: null;
  sales_ref: null;
  reason: null;
  cancel_reason: null;
  delivery_number: null;
  confirmed_at: string;
  shipped_at: string;
  fulfilled_at: string;
  cancelled_at: null;
  allocated_at: string;
  created_at: string;
  updated_at: string;
  is_allocated: number;
  taken_by_customer: number;
  other_reason: null;
  is_kpcpen: null;
  qty_kpcpen: null;
  master_order_id: null;
  easygo_no_do: null;
  biofarma_changed: null;
  service_type: null;
  no_document: null;
  released_date: null;
  notes: null;
  activity_id: number;
  is_manual: null;
  no_po: null;
  created_by: number;
  validated_by: null;
  validated_at: null;
  activity: PutV2OrderIdFulfilled200Activity;
  order_tags: string[];
  order_item_projection_capacities: string[];
  order_items: PutV2OrderIdFulfilled200OrderItemsItem[];
  order_comments: PutV2OrderIdFulfilled200OrderCommentsItem[];
  customer: PutV2OrderIdFulfilled200Customer;
  vendor: PutV2OrderIdFulfilled200Vendor;
  user_confirmed_by: PutV2OrderIdFulfilled200UserConfirmedBy;
  user_shipped_by: PutV2OrderIdFulfilled200UserShippedBy;
  user_fulfilled_by: PutV2OrderIdFulfilled200UserFulfilledBy;
  user_cancelled_by: null;
  user_allocated_by: PutV2OrderIdFulfilled200UserAllocatedBy;
  user_created_by: PutV2OrderIdFulfilled200UserCreatedBy;
  user_updated_by: PutV2OrderIdFulfilled200UserUpdatedBy;
  user_deleted_by: null;
  user_validated_by: null;
};

export const getSmile = () => {
/**
 * @summary Menerima Pesanan
 */
const putV2OrderIdFulfilled = <TData = AxiosResponse<PutV2OrderIdFulfilled200>>(
    id: string,
    putV2OrderIdFulfilledBody: PutV2OrderIdFulfilledBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v2/order/${id}/fulfilled`,
      putV2OrderIdFulfilledBody,options
    );
  }

return {putV2OrderIdFulfilled}};
export type PutV2OrderIdFulfilledResult = AxiosResponse<PutV2OrderIdFulfilled200>
