/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * SMILE
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostUserBody = {
  global_id: number;
  username: string;
  email: string;
  password: string;
  role: number;
  entity_id: number;
  firstname: string;
  lastname: string;
  gender: number;
  date_of_birth: string;
  mobile_phone: string;
  address: string;
  village_id: number;
  timezone_id: number;
  status: number;
  view_only: number;
  manufacture_id: number;
};

export type PostUser201 = {
  role_label: string;
  entity_name: string;
  status_label: string;
  gender_label: string;
  province_name: string;
  regency_name: string;
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
  gender: number;
  date_of_birth: string;
  mobile_phone: string;
  role: number;
  village_id: string;
  entity_id: number;
  timezone_id: number;
  created_by: number;
  updated_by: number;
  status: number;
  last_login: null;
  last_device: null;
  created_at: string;
  updated_at: string;
  address: string;
  view_only: number;
  change_password: number;
  manufacture_id: number;
  fcm_token: null;
};

export type PostUser500 = { [key: string]: unknown };

export type PostAuthUpdatePasswordBody = {
  password: string;
  new_password: string;
  password_confirmation: string;
};

export type PostAuthUpdatePassword200 = {
  message: string;
};

export type PostAuthUpdatePassword500 = { [key: string]: unknown };

export type PutUserIdBody = {
  username: string;
  email: string;
  role: number;
  firstname: string;
  lastname: string;
  mobile_phone: string;
  date_of_birth: string;
  gender: number;
  timezone_id: number;
  village_id: number;
  address: string;
  entity_id: number;
  view_only: number;
  password: string;
  status: number;
  manufacture_id: number;
};

export type PutUserId200 = {
  role_label: string;
  entity_name: string;
  status_label: string;
  gender_label: string;
  province_name: string;
  regency_name: string;
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
  gender: number;
  date_of_birth: string;
  mobile_phone: string;
  role: number;
  village_id: string;
  entity_id: number;
  timezone_id: number;
  created_by: number;
  updated_by: number;
  status: number;
  last_login: null;
  last_device: null;
  created_at: string;
  updated_at: string;
  address: string;
  view_only: number;
  change_password: number;
  manufacture_id: number;
  fcm_token: null;
};

export type PutUserId404 = { [key: string]: unknown };

export type PutUserId500 = { [key: string]: unknown };

export type DeleteUserId200 = {
  message: string;
};

export type DeleteUserId404 = { [key: string]: unknown };

export type DeleteUserId500 = { [key: string]: unknown };

export type PutUserIdStatusBody = {
  status: number;
};

export type PutUserIdStatus200 = {
  role_label: string;
  entity_name: string;
  status_label: string;
  gender_label: string;
  province_name: string;
  regency_name: string;
  id: number;
  username: string;
  email: string;
  firstname: string;
  lastname: string;
  gender: number;
  date_of_birth: string;
  mobile_phone: string;
  role: number;
  village_id: string;
  entity_id: number;
  timezone_id: number;
  created_by: number;
  updated_by: number;
  status: number;
  last_login: null;
  last_device: null;
  created_at: string;
  updated_at: string;
  address: string;
  view_only: number;
  change_password: number;
  manufacture_id: number;
  fcm_token: null;
};

export type PutUserIdStatus404 = { [key: string]: unknown };

export type PutUserIdStatus500 = { [key: string]: unknown };

export const getSmile = () => {
/**
 * This function comment is parsed by doctrine
 * @summary /user
 */
const postUser = <TData = AxiosResponse<PostUser201>>(
    postUserBody: PostUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/user`,
      postUserBody,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary Update Password
 */
const postAuthUpdatePassword = <TData = AxiosResponse<PostAuthUpdatePassword200>>(
    postAuthUpdatePasswordBody: PostAuthUpdatePasswordBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/update-password`,
      postAuthUpdatePasswordBody,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /user/:id
 */
const putUserId = <TData = AxiosResponse<PutUserId200>>(
    id: string,
    putUserIdBody: PutUserIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/user/${id}`,
      putUserIdBody,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /user/:id
 */
const deleteUserId = <TData = AxiosResponse<DeleteUserId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/user/${id}`,options
    );
  }

/**
 * This function comment is parsed by doctrine
 * @summary /user/:id/status
 */
const putUserIdStatus = <TData = AxiosResponse<PutUserIdStatus200>>(
    id: string,
    putUserIdStatusBody: PutUserIdStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/user/${id}/status`,
      putUserIdStatusBody,options
    );
  }

return {postUser,postAuthUpdatePassword,putUserId,deleteUserId,putUserIdStatus}};
export type PostUserResult = AxiosResponse<PostUser201>
export type PostAuthUpdatePasswordResult = AxiosResponse<PostAuthUpdatePassword200>
export type PutUserIdResult = AxiosResponse<PutUserId200>
export type DeleteUserIdResult = AxiosResponse<DeleteUserId200>
export type PutUserIdStatusResult = AxiosResponse<PutUserIdStatus200>
