/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AssetModels {
  asset_type_id: number | null;
  capacity: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  manufacture_id: number | null;
  name: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface Assets {
  asset_type_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number | null;
  id: Generated<number>;
  maintainers_id: number | null;
  manufacture_id: number | null;
  owners_id: number | null;
  production_year: number | null;
  serial_number: string | null;
  status: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface AssetTypes {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string | null;
  type: number | null;
  updated_at: Generated<Date>;
}

export interface Batches {
  code: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  expired_date: Date | null;
  global_id: number | null;
  id: Generated<number>;
  manufacture_id: number | null;
  production_date: Date | null;
  status: Generated<number | null>;
  updated_at: Generated<Date>;
}

export interface BiofarmaOrders {
  alamat: string | null;
  biofarma_id: number | null;
  biofarma_type: string | null;
  code_product_kemenkes: string | null;
  created_at: Generated<Date>;
  entrance_type: string | null;
  exist_smile: number | null;
  expired_date: Date | null;
  grant_country: string | null;
  id: Generated<number>;
  jm_dosis: number | null;
  jm_dosis_terima: number | null;
  jm_vial: number | null;
  jm_vial_terima: number | null;
  kode_area: number | null;
  manufacture_country: string | null;
  no_batch: string | null;
  no_do: string | null;
  no_document: string | null;
  no_po: string | null;
  notes: string | null;
  pengirim: string | null;
  produk: string | null;
  released_date: Date | null;
  service_type: number | null;
  status: string | null;
  tanggal_do: Date | null;
  tanggal_kirim: Date | null;
  tanggal_terima: Date | null;
  tujuan: string | null;
  updated_at: Generated<Date>;
}

export interface BiofarmaOrdersCopy {
  alamat: string | null;
  biofarma_id: number | null;
  biofarma_type: string | null;
  created_at: Generated<Date>;
  exist_smile: number | null;
  expired_date: Date | null;
  id: Generated<number>;
  jm_dosis: number | null;
  jm_dosis_terima: number | null;
  jm_vial: number | null;
  jm_vial_terima: number | null;
  kode_area: number | null;
  no_batch: string | null;
  no_do: string | null;
  no_po: string | null;
  pengirim: string | null;
  produk: string | null;
  status: string | null;
  tanggal_do: Date | null;
  tanggal_kirim: Date | null;
  tanggal_terima: Date | null;
  tujuan: string | null;
  updated_at: Generated<Date>;
}

export interface BiofarmaSmdvOrders {
  alamat: string | null;
  biofarma_id: number;
  created_at: Date;
  deleted_at: Date | null;
  do_pusat: string | null;
  expired_date: Date | null;
  id: Generated<number>;
  jenis_layanan: string | null;
  jumlah_dosis: number | null;
  jumlah_vial: number | null;
  keterangan: string | null;
  kode_area: string | null;
  kode_hub: string | null;
  nama_produk: string | null;
  nama_smdv: string | null;
  no_batch: string | null;
  nomor_do: string | null;
  nomor_po: string | null;
  nomor_surat_alokasi: string | null;
  pengiriman: string | null;
  status: string | null;
  tanggal_do: Date | null;
  tanggal_pickup: Date | null;
  tanggal_terima: Date | null;
  tipe_vaksin: string | null;
  tujuan_pengiriman: string | null;
  updated_at: Date;
}

export interface ColdchainCapacityEquipmentUnused {
  capacity_nett_at_minus_20_c: number | null;
  capacity_nett_at_minus_86_c: number | null;
  capacity_nett_at_plus_5_c: number | null;
  code_pqs: string;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  status: Generated<number | null>;
  updated_at: Date;
  updated_by: number | null;
}

export interface ColdstorageAnnualPlanning {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  id: Generated<number>;
  monthly_volume: number | null;
  monthly_volume_percent: number | null;
  peak_volume_augustus: number | null;
  peak_volume_augustus_percent: number | null;
  peak_volume_november: number | null;
  peak_volume_november_percent: number | null;
  peak_volume_q3: number | null;
  peak_volume_q3_percent: number | null;
  peak_volume_q4: number | null;
  peak_volume_q4_percent: number | null;
  quartal_volume: number | null;
  quartal_volume_percent: number | null;
  updated_at: Date;
  updated_by: number | null;
  year: number;
  yearly_child_id: number | null;
  yearly_volume: number | null;
  yearly_volume_need: number | null;
  yearly_volume_need_percent: number | null;
  yearly_volume_percent: number | null;
}

export interface ColdstorageAnnualPlanningTemperature {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  id: Generated<number>;
  monthly_volume: number | null;
  peak_volume_augustus: number | null;
  peak_volume_november: number | null;
  peak_volume_q3: number | null;
  peak_volume_q4: number | null;
  quartal_volume: number | null;
  range_temperature_id: number;
  updated_at: Date;
  updated_by: number | null;
  year: number;
  yearly_volume: number | null;
  yearly_volume_need: number | null;
}

export interface ColdstorageMaterials {
  coldstorage_id: number | null;
  created_at: Date;
  deleted_at: Date | null;
  dosage_stock: number | null;
  entity_id: number | null;
  id: Generated<number>;
  master_material_id: number | null;
  max_dosage: number | null;
  package_stock: number | null;
  package_volume: number | null;
  projection_package_stock: number | null;
  projection_package_volume: number | null;
  projection_stock: number | null;
  projection_vial_stock: number | null;
  recommend_order_base_on_max: number | null;
  remain_package_fulfill: number | null;
  updated_at: Date;
  vial_stock: number | null;
  volume_per_liter: number | null;
}

export interface ColdstoragePerTemperature {
  coldstorage_id: number | null;
  created_at: Date;
  deleted_at: Date | null;
  entity_id: number | null;
  id: Generated<number>;
  percentage_capacity: number | null;
  projection_percentage_capacity: number | null;
  projection_total_volume: number | null;
  projection_volume_asset: number | null;
  range_temperature_id: number | null;
  total_volume: number | null;
  updated_at: Date;
  volume_asset: number | null;
}

export interface Coldstorages {
  created_at: Date;
  deleted_at: Date | null;
  entity_id: number | null;
  id: Generated<number>;
  percentage_capacity: number | null;
  projection_percentage_capacity: number | null;
  projection_total_volume: number | null;
  projection_volume_asset: number | null;
  total_volume: number | null;
  updated_at: Date;
  volume_asset: number | null;
}

export interface ColdstorageTransactionLogs {
  created_at: Date;
  deleted_at: Date | null;
  entity_id: number | null;
  id: Generated<number>;
  master_material_id: number | null;
  status: number | null;
  updated_at: Date;
}

export interface CommitmentItems {
  commitment_id: number;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  dose_quantity: number;
  id: Generated<number>;
  material_id: number;
  province_id: string;
  service_type_id: number;
  updated_at: Date;
  updated_by: number | null;
  vial_quantity: number;
}

export interface Commitments {
  contract_date: Date;
  contract_number: string;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  information: string | null;
  updated_at: Date;
  updated_by: number | null;
  vendor_id: number;
  year: string;
}

export interface Configurations {
  created_at: Date | null;
  deleted_at: Date | null;
  id: Generated<number>;
  key: string;
  updated_at: Date | null;
  value: string;
}

export interface Contracts {
  contract_number: string;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  updated_at: Date;
  updated_by: number | null;
}

export interface CustomerHasActivities {
  activity_id: number | null;
  created_at: Generated<Date>;
  customer_id: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendors {
  created_at: Generated<Date>;
  customer_id: number | null;
  deleted_at: Date | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  is_extermination: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendors11feb {
  created_at: Generated<Date>;
  customer_id: number | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendors13feb1105 {
  created_at: Generated<Date>;
  customer_id: number | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendors28Juli21 {
  created_at: Generated<Date>;
  customer_id: number | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendors3feb21 {
  created_at: Generated<Date>;
  customer_id: number | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface CustomerVendorsBackup30734 {
  created_at: Generated<Date>;
  customer_id: number | null;
  is_consumption: Generated<number>;
  is_distribution: Generated<number>;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface DashboardSatusehat {
  api_url: string | null;
  created_at: Date;
  created_by: number | null;
  dashboard_name: string | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  sort: number | null;
  updated_at: Date;
  updated_by: number | null;
  uuid: string;
}

export interface DeleteBiofarma {
  alamat: string | null;
  created_at: Generated<Date>;
  expired_date: Date | null;
  jenis_layanan: number | null;
  jm_dosis: number | null;
  jm_dosis_terima: number | null;
  jm_vial: number | null;
  jm_vial_terima: number | null;
  keterangan: string | null;
  kode_area: number | null;
  no_batch: string | null;
  no_do: string;
  no_po: string | null;
  no_surat: string | null;
  pengirim: string | null;
  produk: string | null;
  status: string | null;
  tanggal_do: Date | null;
  tanggal_kirim: Date | null;
  tanggal_release: Date | null;
  tanggal_terima: Date | null;
  tujuan: string | null;
  type: string | null;
  updated_at: Generated<Date>;
}

export interface DinOrderItems {
  created_at: Date;
  din_order_id: number | null;
  entrance_type: string | null;
  expired_date: Date | null;
  grant_country: string | null;
  id: Generated<number>;
  jm_dosis: number | null;
  jm_dosis_terima: number | null;
  jm_vial: number | null;
  jm_vial_terima: number | null;
  keterangan: string | null;
  kfa_code: string | null;
  lot_no: string | null;
  manufacture_country: string | null;
  no_batch: string | null;
  note: string | null;
  product_code: string | null;
  production_date: Date | null;
  produk: string | null;
  released_date: Date | null;
  tanggal_release: Date | null;
  total_price: number | null;
  unit: string | null;
  unit_price: number | null;
  updated_at: Date;
}

export interface DinOrders {
  activity_code: string | null;
  alamat: string | null;
  alamat_penerima: string | null;
  alamat_pengirim: string | null;
  biaya_transport: number | null;
  biofarma_id: number | null;
  carrier: string | null;
  carrier_ref: string | null;
  created_at: Date;
  din_type: string | null;
  exist_smile: number | null;
  id: Generated<number>;
  jenis_layanan: string | null;
  kabkota_id_penerima: number | null;
  kabkota_id_pengirim: number | null;
  kabkota_penerima: string | null;
  kabkota_pengirim: string | null;
  kecamatan_id_penerima: number | null;
  kecamatan_id_pengirim: number | null;
  kecamatan_penerima: string | null;
  kecamatan_pengirim: string | null;
  kelurahan_id_penerima: number | null;
  kelurahan_id_pengirim: number | null;
  kelurahan_penerima: string | null;
  kelurahan_pengirim: string | null;
  key_ssl: string | null;
  kode_area: number | null;
  kode_penerima: string | null;
  kode_pengirim: string | null;
  kodepos_penerima: string | null;
  kodepos_pengirim: string | null;
  line: string | null;
  line_ref: string | null;
  nama_pengirim: string | null;
  no_do: string | null;
  no_document: string | null;
  no_po: string | null;
  notes: string | null;
  pengirim: string | null;
  provinsi_id_penerima: number | null;
  provinsi_id_pengirim: number | null;
  provinsi_penerima: string | null;
  provinsi_pengirim: string | null;
  service_type: string | null;
  status: string | null;
  sumber_dana: string | null;
  tanggal_do: Date | null;
  tanggal_kirim: Date | null;
  tanggal_terima: Date | null;
  total_transaksi: number | null;
  tujuan: string | null;
  type_penerima: string | null;
  updated_at: Date;
}

export interface DownloadLogs {
  created_at: Date;
  deleted_at: Date | null;
  download_url: string | null;
  id: Generated<number>;
  status: number;
  updated_at: Date;
  user_id: number;
}

export interface DummyBiofarma {
  alamat: string | null;
  created_at: Generated<Date>;
  expired_date: Date | null;
  jenis_layanan: number | null;
  jm_dosis: number | null;
  jm_dosis_terima: number | null;
  jm_vial: number | null;
  jm_vial_terima: number | null;
  keterangan: string | null;
  kode_area: number | null;
  no_batch: string | null;
  no_do: string;
  no_po: string | null;
  no_surat: string | null;
  pengirim: string | null;
  produk: string | null;
  status: string | null;
  tanggal_do: Date | null;
  tanggal_kirim: Date | null;
  tanggal_release: Date | null;
  tanggal_terima: Date | null;
  tujuan: string | null;
  type: string | null;
  updated_at: Generated<Date>;
}

export interface Entities {
  accuracy: string | null;
  address: string | null;
  bpom_key: string | null;
  code: string | null;
  code_new: string | null;
  code_old: string | null;
  code_satu_sehat: string | null;
  country: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  global_id: number | null;
  gps_errors: string | null;
  id: Generated<number>;
  is_ayosehat: Generated<number>;
  is_puskesmas: Generated<number | null>;
  is_vendor: Generated<number>;
  lat: string | null;
  lng: string | null;
  name: string | null;
  postal_code: string | null;
  province_id: string | null;
  province_id_new: string | null;
  province_id_old: string | null;
  regency_id: string | null;
  regency_id_new: string | null;
  regency_id_old: string | null;
  region_id: number | null;
  rutin_join_date: Date | null;
  status: Generated<number | null>;
  sub_district_id: string | null;
  sub_district_id_new: string | null;
  sub_district_id_old: string | null;
  type: Generated<number | null>;
  updated_at: Generated<Date>;
  updated_by: number | null;
  village_id: string | null;
  village_id_new: string | null;
  village_id_old: string | null;
  ws_global_id: number | null;
}

export interface EntityActivityDate {
  activity_id: number;
  created_at: Date;
  deleted_at: Date | null;
  end_date: Date | null;
  entity_id: number;
  id: Generated<number>;
  join_date: Date | null;
  updated_at: Date;
}

export interface EntityEntityTags {
  created_at: Generated<Date>;
  entity_id: number;
  entity_tag_id: number;
  id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface EntityHasMasterMaterials {
  allocated_stock: Generated<number>;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number | null;
  extermination_discard_qty: Generated<number>;
  extermination_qty: Generated<number>;
  extermination_received_qty: Generated<number>;
  extermination_shipped_qty: Generated<number>;
  id: Generated<number>;
  master_material_id: number | null;
  max: Generated<number>;
  min: Generated<number>;
  on_hand_stock: Generated<number>;
  stock_last_update: Date | null;
  total_open_vial: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface EntityMasterMaterialActivities {
  activity_id: number | null;
  allocated: Generated<number | null>;
  consumption_rate: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  entity_master_material_id: number | null;
  global_id: number | null;
  id: Generated<number>;
  max: Generated<number | null>;
  min: Generated<number | null>;
  retailer_price: number | null;
  stock_on_hand: Generated<number | null>;
  tax: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface EntityMasterMaterialMinmax {
  created_at: Generated<Date | null>;
  created_by: number;
  deleted_at: Date | null;
  emma_id: number;
  id: Generated<number>;
  max: number;
  min: number;
  updated_at: Generated<Date | null>;
  updated_by: number;
  year: number | null;
  yearly_plan_id: number;
}

export interface EntityTags {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface EntityTagsOld {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface EventReportChildReasons {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  parent_id: number | null;
  title: string | null;
  updated_at: Generated<Date>;
}

export interface EventReportComments {
  comment: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  event_report_id: number | null;
  id: Generated<number>;
  status: number | null;
  updated_at: Generated<Date>;
  user_id: number | null;
}

export interface EventReportHistories {
  created_at: Generated<Date>;
  event_report_id: number;
  id: Generated<number>;
  status: number;
  updated_at: Generated<Date>;
  updated_by: number;
}

export interface EventReportItems {
  child_reason_id: number | null;
  created_at: Generated<Date>;
  custom_material: string | null;
  deleted_at: Date | null;
  event_report_id: number;
  expired_date: Date | null;
  id: Generated<number>;
  material_id: number | null;
  no_batch: string | null;
  production_date: Date | null;
  qty: Generated<number>;
  reason_id: number | null;
  updated_at: Generated<Date>;
}

export interface EventReportReasons {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string | null;
  updated_at: Generated<Date>;
}

export interface EventReports {
  arrived_date: Date;
  canceled_at: Date | null;
  canceled_by: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  finished_at: Date | null;
  finished_by: number | null;
  has_order: Generated<number>;
  id: Generated<number>;
  link: string | null;
  no_packing_slip: string | null;
  order_id: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface ExterminationFlowReasons {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  flow_id: number | null;
  id: Generated<number>;
  transaction_reason_id: number | null;
  updatedAt: Generated<Date>;
}

export interface ExterminationFlows {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  title: string | null;
  updatedAt: Generated<Date>;
}

export interface ExterminationTransactions {
  activity_id: number;
  change_qty: Generated<number>;
  close_vial: Generated<number>;
  created_by: number | null;
  createdAt: Generated<Date>;
  customer_id: number | null;
  deleted_at: Date | null;
  entity_id: number;
  extermination_transaction_type_id: number;
  flow_id: Generated<number | null>;
  id: Generated<number>;
  master_material_id: number;
  material_id: number | null;
  open_vial: Generated<number>;
  opening_qty: Generated<number>;
  order_id: number | null;
  stock_extermination_id: number;
  updated_by: number | null;
  updatedAt: Generated<Date>;
  vendor_id: number | null;
}

export interface ExterminationTransactionTypes {
  created_at: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface IntegrationAsikAggregate {
  aggregate: number | null;
  batch_code_smile: string | null;
  batch_id_smile: number | null;
  batch_number_asik: string | null;
  createdAt: Date;
  customer_id: number | null;
  deletedAt: Date | null;
  id: Generated<number>;
  injection_date: Date | null;
  input_date: Date | null;
  master_material_id: number | null;
  page: number | null;
  pos_imunisasi_asik: string | null;
  pos_imunisasi_asik_province_id: number | null;
  pos_imunisasi_asik_regency_id: number | null;
  pos_imunisasi_asik_subdistrict_id: number | null;
  puskesmas_asik: string | null;
  puskesmas_asik_province_id: number | null;
  puskesmas_asik_regency_id: number | null;
  puskesmas_asik_subdistrict_id: number | null;
  updatedAt: Date | null;
  vaksin_asik: string | null;
  vendor_id: number | null;
}

export interface IntegrationAyoSehat {
  activity_id: number | null;
  batch_id: number | null;
  consumed_qty: number | null;
  consumed_qty_closevial: number | null;
  consumed_qty_openvial: number | null;
  consumed_status: number | null;
  created_at: Generated<Date>;
  created_at_consumed_smile: Date | null;
  created_at_injection: Date | null;
  created_at_return_vaccination: Date | null;
  created_by: number | null;
  customer_id: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  injection_qty: number | null;
  integration_status: Generated<number>;
  material_id: number | null;
  return_qty: number | null;
  return_qty_closevial: number | null;
  return_qty_openvial: number | null;
  return_status: number | null;
  return_validation: number | null;
  session_id: string | null;
  status_vvm: number | null;
  stock_id: number | null;
  transaction_id_consumed: number | null;
  transaction_id_injection: number | null;
  transaction_id_return: number | null;
  updated_at: Generated<Date>;
  updated_at_return_vaccination: Date | null;
  vendor_id: number | null;
}

export interface IntegrationEmonevMaterials {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  master_material_id: number | null;
  nama_xls: string | null;
  obat_id: string | null;
  tahun: number | null;
  type_rop: string | null;
  updatedAt: Generated<Date>;
  uraian: string | null;
}

export interface IntegrationEmonevProvinces {
  code: string | null;
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  name: string | null;
  npwp: string | null;
  permit: string | null;
  permit_date: Date | null;
  pic: string | null;
  pic_email: string | null;
  pic_phone: string | null;
  pimpinan: string | null;
  pimpinan_email: string | null;
  pimpinan_phone: string | null;
  province_id: number;
  trader_id: string | null;
  updatedAt: Generated<Date>;
}

export interface IntegrationEmonevRegencies {
  bps_regency_id: Generated<number | null>;
  code: string | null;
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  name: string | null;
  npwp: string | null;
  permit: string | null;
  permit_date: Date | null;
  pic: string | null;
  pic_email: string | null;
  pic_phone: string | null;
  pimpinan: string | null;
  pimpinan_email: string | null;
  pimpinan_phone: string | null;
  regency_id: number | null;
  trader_id: string | null;
  updatedAt: Generated<Date>;
}

export interface IntegrationOrderItems {
  confirmed_qty: number | null;
  created_at: Date;
  created_by: number;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  integration_order_id: number;
  master_material_id: number;
  other_reason: string | null;
  qty: number;
  reason_id: number | null;
  recomended_stock: number | null;
  updated_at: Date;
  updated_by: number;
}

export interface IntegrationOrderItemsKfa {
  code_kfa_product_template: string;
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  integration_order_id: number;
  product_code: string;
  qty: number;
  reason_id: number | null;
  updated_at: Date;
}

export interface IntegrationOrders {
  activity_id: number;
  created_at: Date;
  customer_id: number;
  deleted_at: Date | null;
  existing_smile_order_id: number;
  id: Generated<number>;
  key_ssl: string | null;
  status: number;
  type: number;
  updated_at: Date;
  vendor_id: number;
}

export interface InventoryOverviews {
  created_at: Generated<Date>;
  date: Date | null;
  entity_tag_id: number | null;
  habis: number | null;
  id: Generated<number>;
  material: number | null;
  max: number | null;
  min: number | null;
  normal: number | null;
  province_id: number | null;
  province_name: string | null;
  regency_id: number | null;
  regency_name: string | null;
  updated_at: Generated<Date>;
}

export interface KfaLevels {
  code: number | null;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  order_number: number | null;
  updated_at: Date;
  updated_by: number | null;
}

export interface LogEntityMaterialImports {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  file: string;
  id: Generated<number>;
  notes: string;
  status: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface LoginAttempts {
  created_at: Generated<Date>;
  hit: number;
  id: Generated<number>;
  ip: string;
  last_attempt: Generated<Date | null>;
  updated_at: Generated<Date>;
}

export interface Manufactures {
  address: string | null;
  contact_name: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  description: string | null;
  email: string | null;
  global_id: number | null;
  id: Generated<number>;
  is_asset: Generated<number>;
  name: string | null;
  phone_number: string | null;
  production_date: Date | null;
  production_year: number | null;
  reference_id: string | null;
  status: Generated<number | null>;
  type: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
  village_id: string | null;
  ws_global_id: number | null;
}

export interface ManufactureTypes {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Date>;
}

export interface MappingCancelDiscard {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  transaction_cancel_discard_id: number;
  transaction_discard_id: number;
  updated_at: Date;
}

export interface MappingEntities {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  id_bpjs: number | null;
  id_entitas_smile: number | null;
  id_pusdatin: number | null;
  id_satu_sehat: number | null;
  updated_at: Date;
}

export interface MappingMasterMaterials {
  asik_name: string | null;
  code_biofarma: string | null;
  code_bpom: string | null;
  code_kfa_ingredients: string | null;
  code_kfa_packaging: string | null;
  code_kfa_product_template: string | null;
  code_kfa_product_variant: string | null;
  code_siha: string | null;
  code_sitb: string | null;
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  id_kfa: string | null;
  id_material_smile: number | null;
  name_kfa_ingredients: string | null;
  name_kfa_packaging: string | null;
  name_kfa_product_template: string | null;
  name_kfa_product_variant: string | null;
  name_material_smile: string | null;
  name_siha: string | null;
  name_sitb: string | null;
  updated_at: Date;
}

export interface MasterActivities {
  code: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  global_id: number | null;
  id: Generated<number>;
  is_ordered_purchase: Generated<number>;
  is_ordered_sales: Generated<number>;
  is_patient_id: Generated<number | null>;
  name: string | null;
  program_id: Generated<number | null>;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MasterIpvs {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  has_ipv: Generated<number | null>;
  id: Generated<number>;
  ipv: Generated<Decimal>;
  master_material_id: number | null;
  material_id: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MasterIpvsCopy {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  has_ipv: Generated<number | null>;
  id: Generated<number>;
  ipv: Generated<Decimal>;
  master_material_id: number | null;
  material_id: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MasterKodeWilayah {
  code: string | null;
  kode_bps: string | null;
  kode_lama: string | null;
  level: number | null;
  name: string | null;
  parent: string | null;
  state: string | null;
}

export interface MasterMaterialHasActivities {
  activity_id: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_sequence: number | null;
  master_material_id: number | null;
  updated_at: Generated<Date>;
}

export interface MasterMaterialHasCompanions {
  created_at: Generated<Date>;
  id: Generated<number>;
  master_material_companion_id: number | null;
  master_material_id: number | null;
  updated_at: Generated<Date>;
}

export interface MasterMaterialHasConditions {
  created_at: Generated<Date>;
  id: Generated<number>;
  key: string | null;
  master_material_id: number | null;
  type: number | null;
  updated_at: Generated<Date>;
  value: string | null;
}

export interface MasterMaterialHasManufactures {
  created_at: Generated<Date>;
  id: Generated<number>;
  manufacture_id: number | null;
  master_material_id: number | null;
  updated_at: Generated<Date>;
}

export interface MasterMaterials {
  bpom_code: string | null;
  code: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  description: string | null;
  global_id: number | null;
  id: Generated<number>;
  is_addremove: Generated<number>;
  is_openvial: Generated<number>;
  is_stockcount: Generated<number>;
  is_vaccine: Generated<number>;
  kfa_code: string | null;
  kfa_level_id: number | null;
  managed_in_batch: Generated<number>;
  max_retail_price: Generated<number | null>;
  min_retail_price: Generated<number | null>;
  name: string | null;
  need_sequence: number | null;
  parent_id: number | null;
  pieces_per_unit: Generated<number>;
  range_temperature_id: number | null;
  status: Generated<number>;
  temperature_max: number | null;
  temperature_min: number | null;
  temperature_sensitive: number | null;
  unit: string | null;
  unit_of_distribution: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  ws_global_id: number | null;
}

export interface MasterMaterialType {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  name: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MasterTarget {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Date>;
}

export interface MasterTargetDistributions {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  master_material_id: number | null;
  master_target_id: number;
  material_id: number | null;
  qty: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MasterTargetRegencies {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  id: Generated<number>;
  master_target_id: number;
  qty: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
  year: string;
}

export interface MasterVolumeMaterialManufactures {
  box_height: number | null;
  box_length: number | null;
  box_width: number | null;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  manufacture_id: number | null;
  master_material_id: number | null;
  pieces_per_unit: number | null;
  unit_per_box: number | null;
  updated_at: Date;
  updated_by: number | null;
}

export interface MaterialCategories {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  name: string;
  updated_at: Date;
}

export interface MaterialCompanions {
  created_at: Generated<Date>;
  id: Generated<number>;
  material_companion_id: number;
  material_id: number;
  updated_at: Generated<Date>;
}

export interface MaterialConditions {
  created_at: Generated<Date>;
  id: Generated<number>;
  key: string;
  material_id: number | null;
  type: Generated<number>;
  updated_at: Generated<Date>;
  value: string;
}

export interface MaterialEntity {
  abnormality_duration_days: number | null;
  abnormality_type: string | null;
  allocated_qty: Generated<number>;
  consumption_rate: number | null;
  consumption_rate_month: number | null;
  consumption_rate_week: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  days_stock: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  demand_forecast: number | null;
  entity_id: number | null;
  id: Generated<number>;
  inventory_policy: string | null;
  lead_time_days: number | null;
  lead_time_demand: number | null;
  material_id: number | null;
  max: number | null;
  max_updated_at: Date | null;
  min: number | null;
  min_updated_at: Date | null;
  on_hand_qty: Generated<number>;
  optimal_order_quantity: number | null;
  order_periodicity_days: number | null;
  retailer_price: number | null;
  retailer_price_updated_at: Date | null;
  safety_stock: number | null;
  service_level: number | null;
  tax: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MaterialManufacture {
  created_at: Generated<Date>;
  id: Generated<number>;
  manufacture_id: number | null;
  material_id: number | null;
  updated_at: Generated<Date>;
}

export interface MaterialMaterialCategories {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  master_material_id: number;
  material_category_id: number;
  updated_at: Date;
}

export interface MaterialMaterialTag {
  created_at: Generated<Date>;
  id: Generated<number>;
  material_id: number | null;
  material_tag_id: number | null;
  updated_at: Generated<Date>;
}

export interface Materials {
  bpom_code: number | null;
  code: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  description: string | null;
  id: Generated<number>;
  is_addremove: Generated<number>;
  is_stockcount: Generated<number | null>;
  is_vaccine: Generated<number>;
  managed_in_batch: Generated<number>;
  master_activity_id: number | null;
  master_material_id: number | null;
  name: string | null;
  pieces_per_unit: Generated<number>;
  status: Generated<number | null>;
  temperature_max: number | null;
  temperature_min: number | null;
  temperature_sensitive: number | null;
  unit: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface Materialss {
  bpom_code: number | null;
  code: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  description: string | null;
  id: Generated<number>;
  is_addremove: Generated<number>;
  is_stockcount: Generated<number | null>;
  is_vaccine: Generated<number>;
  managed_in_batch: Generated<number>;
  name: string | null;
  pieces_per_unit: Generated<number>;
  status: Generated<number | null>;
  temperature_max: number | null;
  temperature_min: number | null;
  temperature_sensitive: number | null;
  unit: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface MaterialTags {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  is_ordered_purchase: Generated<number | null>;
  is_ordered_sales: Generated<number | null>;
  title: string | null;
  updated_at: Generated<Date>;
}

export interface NewOpnameItems {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  master_material_id: number | null;
  material_id: number | null;
  new_opname_id: number;
  updated_at: Generated<Date>;
}

export interface NewOpnames {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  id: Generated<number>;
  period_id: number | null;
  status: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface NewOpnameStocks {
  batch_code: string | null;
  batch_id: number | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  expired_date: Date | null;
  id: Generated<number>;
  new_opname_item_id: number;
  real_qty: Generated<number>;
  smile_qty: Generated<number>;
  stock_id: number | null;
  unsubmit_distribution_qty: Generated<number>;
  unsubmit_return_qty: Generated<number>;
  updated_at: Generated<Date>;
}

export interface NotificationTypes {
  created_at: Generated<Date | null>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string;
  title_en: string | null;
  type: string;
  updated_at: Generated<Date | null>;
}

export interface OpnameActions {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OpnameItemReasonActions {
  created_at: Generated<Date>;
  id: Generated<number>;
  opname_action_id: number | null;
  opname_reason_id: number | null;
  opname_stock_item_id: number | null;
  updated_at: Generated<Date>;
}

export interface OpnamePeriod {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  end_date: Date | null;
  id: Generated<number>;
  month_periode: number | null;
  start_date: Date | null;
  status: Generated<number | null>;
  updated_at: Date;
  updated_by: number | null;
  year_periode: number | null;
}

export interface OpnameReasons {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OpnameStockItems {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  opname_stock_id: number | null;
  real_qty: Generated<number>;
  smile_qty: Generated<number>;
  stock_category: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OpnameStocks {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  end_date: Date;
  entity_id: number;
  id: Generated<number>;
  material_id: number;
  start_date: Date;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OrderComments {
  comment: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  order_id: number;
  order_status: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  user_id: number;
}

export interface OrderHistories {
  created_at: Generated<Date>;
  id: Generated<number>;
  order_id: number | null;
  status: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OrderItemProjectionCapacities {
  capacity_asset: number | null;
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  is_confirm: Generated<number>;
  order_id: number;
  percent_capacity: number | null;
  total_volume: number | null;
  updated_at: Date;
  updated_by: number | null;
}

export interface OrderItems {
  confirmed_qty: Generated<number>;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  master_material_id: number | null;
  material_id: number | null;
  order_id: number;
  order_item_kfa_id: number | null;
  other_reason: string | null;
  qty: number | null;
  reason_id: number | null;
  recommended_stock: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OrderItemsKfa {
  code_kfa_product_template: string | null;
  confirmed_qty: number | null;
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  order_id: number;
  other_reason: string | null;
  qty: number | null;
  reason_id: number | null;
  recomended_stock: number | null;
  updated_at: Date;
}

export interface OrderOrderTag {
  created_at: Generated<Date>;
  id: Generated<number>;
  order_id: number | null;
  order_tag_id: number | null;
  updated_at: Generated<Date>;
}

export interface OrderReports {
  arrived_date: Date | null;
  arrived_qty: number;
  batch_code: string | null;
  batch_expired: Date | null;
  batch_production: Date | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  entity_id: number | null;
  id: Generated<number>;
  material_id: number | null;
  message: string | null;
  updated_at: Generated<Date>;
}

export interface Orders {
  activity_id: number | null;
  actual_shipment: Date | null;
  allocated_at: Date | null;
  allocated_by: number | null;
  biofarma_changed: number | null;
  cancel_reason: number | null;
  cancelled_at: Date | null;
  cancelled_by: number | null;
  confirmed_at: Date | null;
  confirmed_by: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  customer_id: number;
  deleted_at: Date | null;
  deleted_by: number | null;
  delivery_number: string | null;
  device_type: number | null;
  easygo_no_do: string | null;
  estimated_date: Date | null;
  fulfilled_at: Date | null;
  fulfilled_by: number | null;
  global_id: number | null;
  id: Generated<number>;
  is_allocated: Generated<number | null>;
  is_kpcpen: number | null;
  is_manual: number | null;
  master_order_id: number | null;
  no_document: string | null;
  no_po: string | null;
  notes: string | null;
  other_reason: string | null;
  purchase_ref: string | null;
  qty_kpcpen: number | null;
  reason: number | null;
  released_date: Date | null;
  required_date: Date | null;
  sales_ref: string | null;
  service_type: number | null;
  shipped_at: Date | null;
  shipped_by: number | null;
  status: number;
  submit_kpcpen_at: Date | null;
  taken_by_customer: Generated<number | null>;
  track_device_id: number | null;
  type: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
  vendor_id: number;
}

export interface OrderStockExterminations {
  allocated_discard_qty: Generated<number>;
  allocated_received_qty: Generated<number>;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  order_stock_id: number | null;
  received_qty: Generated<number>;
  status: number;
  stock_extermination_id: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OrderStockPurchase {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  order_stock_id: number | null;
  pieces_purchase_id: number | null;
  price: number | null;
  source_material_id: number | null;
  total_price: number | null;
  updated_at: Date;
  year: number | null;
}

export interface OrderStocks {
  allocated_qty: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  fulfill_reason: number | null;
  fulfill_status: number | null;
  id: Generated<number>;
  order_item_id: number | null;
  ordered_qty: number | null;
  other_reason: string | null;
  qrcode: string | null;
  received_qty: number | null;
  status: number | null;
  stock_id: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface OrderTags {
  created_at: Generated<Date>;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface Patients {
  created_at: Generated<Date | null>;
  deleted_at: Date | null;
  entity_id: number | null;
  global_id: number | null;
  id: Generated<number>;
  identity_type: Generated<number>;
  last_preexposure_at: Date | null;
  last_vaccine_at: Date | null;
  nik: string | null;
  phone_number: string | null;
  preexposure_sequence: number | null;
  stop_notification: Generated<number | null>;
  updated_at: Generated<Date | null>;
  vaccine_method: number | null;
  vaccine_sequence: number | null;
}

export interface PiecesPurchase {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  name: string | null;
  updated_at: Date | null;
}

export interface Provinces {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  lat: string | null;
  lng: string | null;
  name: string | null;
  province_id_new: string | null;
  province_id_old: string | null;
  updated_at: Generated<Date>;
  zoom: string | null;
}

export interface RabiesVaccineRules {
  active_duration: number | null;
  created_at: Date | null;
  deleted_at: Date | null;
  end_notification: number | null;
  id: Generated<number>;
  next_duration: number | null;
  sequence: number;
  start_notification: number | null;
  updated_at: Date;
}

export interface RangeTemperature {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  temperature_max: number;
  temperature_min: number;
  updated_at: Date;
  updated_by: number | null;
}

export interface Reconciliation {
  activity_id: number;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  end_date: Date;
  entity_id: number;
  id: Generated<number>;
  master_material_id: number;
  start_date: Date;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface ReconciliationItemReasonActions {
  action_id: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  reason_id: number | null;
  reconciliation_item_id: number | null;
  updated_at: Generated<Date>;
}

export interface ReconciliationItems {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  real_qty: Generated<number | null>;
  reconciliation_id: number;
  smile_qty: Generated<number | null>;
  stock_category: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface Regencies {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  lat: string | null;
  lng: string | null;
  name: string | null;
  province_id: string | null;
  province_id_new: string | null;
  province_id_old: string | null;
  regency_id_new: string | null;
  regency_id_old: string | null;
  updated_at: Generated<Date>;
}

export interface RegenciesBackup {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  lat: string | null;
  lng: string | null;
  name: string | null;
  province_id: string | null;
  updated_at: Generated<Date>;
}

export interface RegionConversionProvince {
  bps_code: string | null;
  bps_name: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  kemendagri_code: string | null;
  kemendagri_name: string | null;
  updated_at: Generated<Date>;
}

export interface RegionConversionRegencies {
  bps_code: string | null;
  bps_name: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  kemendagri_code: string | null;
  kemendagri_name: string | null;
  updated_at: Generated<Date>;
}

export interface RegionConversionSubdistricts {
  bps_code: string | null;
  bps_name: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  kemendagri_code: string | null;
  kemendagri_name: string | null;
  updated_at: Generated<Date>;
}

export interface RegionConversionVillages {
  bps_code: string | null;
  bps_name: string | null;
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  kemendagri_code: string | null;
  kemendagri_name: string | null;
  updated_at: Generated<Date>;
}

export interface Regions {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  name: string | null;
  parent_id: number | null;
  type: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface RequestOrderItems {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  material_id: number | null;
  qty: Generated<number>;
  request_order_id: number | null;
  updated_at: Generated<Date>;
}

export interface RequestOrders {
  buffer_tag: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  customer_id: number;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  sales_ref: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  vendor_id: number;
}

export interface ResetPasswords {
  createdAt: Generated<Date>;
  email: string | null;
  expired_at: Date | null;
  id: Generated<number>;
  token: string | null;
  updatedAt: Generated<Date>;
}

export interface Roles {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Date>;
}

export interface SequelizeMeta {
  name: string;
}

export interface ServiceTypes {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  name: string;
  updated_at: Date;
}

export interface SourceMaterials {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  description: string | null;
  global_id: number | null;
  id: Generated<number>;
  name: string | null;
  updated_at: Date | null;
  updated_by: number | null;
  ws_global_id: number | null;
}

export interface StockExterminations {
  created_by: number | null;
  createdAt: Generated<Date>;
  extermination_discard_qty: Generated<number>;
  extermination_qty: Generated<number>;
  extermination_received_qty: Generated<number>;
  extermination_shipped_qty: Generated<number>;
  global_id: number | null;
  id: Generated<number>;
  stock_id: number | null;
  transaction_reason_id: number | null;
  updated_by: number | null;
  updatedAt: Generated<Date>;
}

export interface StockIntervals {
  change_qty: number | null;
  closing_qty: number | null;
  created_at: Generated<Date>;
  current_stock: number | null;
  customer_id: number | null;
  date: Date | null;
  deleted_at: Date | null;
  entity_id: number | null;
  entity_name: string | null;
  entity_province_id: number | null;
  entity_province_name: string | null;
  entity_regency_id: number | null;
  entity_regency_name: string | null;
  entity_sub_district_id: number | null;
  entity_sub_district_name: string | null;
  entity_tags: string | null;
  entity_village_id: number | null;
  entity_village_name: string | null;
  id: Generated<number>;
  material_entity_id: number | null;
  material_id: number | null;
  material_name: string | null;
  material_tags: string | null;
  max: number | null;
  min: number | null;
  opening_qty: number | null;
  order_id: number | null;
  status_condition: string | null;
  stock_id: number | null;
  transaction_id: number | null;
  transaction_type_id: number | null;
  updated_at: Generated<Date>;
  vendor_id: number | null;
}

export interface Stocks {
  activity_id: number | null;
  allocated: Generated<number | null>;
  batch_id: number | null;
  budget_source: number | null;
  created_by: number | null;
  createdAt: Generated<Date>;
  entity_has_material_id: number | null;
  extermination_discard_qty: Generated<number>;
  extermination_qty: Generated<number>;
  extermination_received_qty: Generated<number>;
  extermination_shipped_qty: Generated<number>;
  global_id: number | null;
  id: Generated<number>;
  in_transit: number | null;
  material_entity_id: number | null;
  open_vial: Generated<number>;
  price: number | null;
  qty: number;
  status: number | null;
  total_price: number | null;
  updated_by: number | null;
  updatedAt: Generated<Date>;
  year: number | null;
}

export interface StopNotificationHistories {
  created_at: Date;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  patient_id: number;
  reason_id: number;
  stop_status: Generated<number | null>;
  updated_at: Date;
  updated_by: number | null;
}

export interface StopNotificationReasons {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string | null;
  type: Generated<string | null>;
  updated_at: Date;
}

export interface SubDistricts {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  name: string | null;
  regency_id: string | null;
  regency_id_new: string | null;
  regency_id_old: string | null;
  sub_district_id_new: string | null;
  sub_district_id_old: string | null;
  updated_at: Generated<Date>;
}

export interface SubDistrictsBackup {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  name: string | null;
  regency_id: string | null;
  updated_at: Generated<Date>;
}

export interface Timezones {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string | null;
  updated_at: Generated<Date>;
  utc_relative: number | null;
}

export interface TrackDevices {
  created_at: Generated<Date>;
  device_number: string | null;
  entity_id: number | null;
  id: Generated<number>;
  mobile_phone: string | null;
  nopol: string | null;
  updated_at: Generated<Date>;
}

export interface TrackingLogEg {
  created_at: Generated<Date>;
  curr_temp: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  is_alarm: number | null;
  lat: number | null;
  lon: number | null;
  no_do: string | null;
  nopol: string | null;
  status_do: string | null;
  updated_at: Generated<Date>;
  updated_time: Date;
  vehicle_status: number | null;
}

export interface TransactionInjections {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  dose_1: number | null;
  dose_2: number | null;
  dose_booster: number | null;
  dose_routine: number | null;
  id: Generated<number>;
  transaction_id: number;
  updated_at: Generated<Date>;
}

export interface TransactionItems {
  created_at: Generated<Date>;
  created_by: number | null;
  id: Generated<number>;
  stock_id: number;
  transaction_id: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
}

export interface TransactionLogs {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  /**
   * 1 = start, 2 = finish
   */
  type: number | null;
  updatedAt: Generated<Date>;
}

export interface TransactionPatients {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  patient_id: number;
  phone_number: string | null;
  transaction_date: Date | null;
  transaction_id: number;
  transaction_type_id: number | null;
  updated_at: Date;
  vaccine_method: number | null;
  vaccine_sequence: number | null;
}

export interface TransactionPurchase {
  created_at: Date;
  deleted_at: Date | null;
  id: Generated<number>;
  pieces_purchase_id: number | null;
  price: number | null;
  source_material_id: number | null;
  total_price: number | null;
  transaction_id: number | null;
  updated_at: Date | null;
  year: number | null;
}

export interface TransactionReasons {
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  global_id: number | null;
  id: Generated<number>;
  is_other: Generated<number>;
  is_purchase: Generated<number | null>;
  title: string | null;
  title_en: string | null;
  transaction_type_id: number | null;
  updatedAt: Generated<Date>;
}

export interface Transactions {
  activity_id: number | null;
  actual_transaction_date: Date | null;
  booster: number | null;
  change_qty: number;
  close_vial: number | null;
  created_by: number | null;
  createdAt: Generated<Date>;
  customer_id: number | null;
  customerCode: string | null;
  deleted_at: Date | null;
  device_type: Generated<number>;
  dose_1: number | null;
  dose_2: number | null;
  entity_id: number;
  global_id: number | null;
  id: Generated<number>;
  master_material_id: number | null;
  material_id: number | null;
  open_vial: number | null;
  opening_qty: number;
  order_id: number | null;
  other_reason: string | null;
  patient_id: number | null;
  preexposure_method: number | null;
  stock_id: number;
  transaction_reason_id: number | null;
  transaction_type_id: number;
  updated_by: number | null;
  updatedAt: Generated<Date>;
  vaccine_sequence: number | null;
  vendor_id: number | null;
}

export interface Transactions13122022 {
  activity_id: number | null;
  booster: number | null;
  change_qty: number;
  close_vial: number | null;
  created_by: number | null;
  createdAt: Generated<Date>;
  customer_id: number | null;
  customerCode: string | null;
  deleted_at: Date | null;
  device_type: Generated<number>;
  dose_1: number | null;
  dose_2: number | null;
  entity_id: number;
  id: number;
  master_material_id: number | null;
  material_id: number | null;
  open_vial: number | null;
  opening_qty: number;
  order_id: number | null;
  other_reason: string | null;
  stock_id: number;
  transaction_reason_id: number | null;
  transaction_type_id: number;
  updated_by: number | null;
  updatedAt: Generated<Date>;
  vendor_id: number | null;
}

export interface TransactionsLast3months {
  activity_id: number | null;
  actual_transaction_date: Date | null;
  booster: number | null;
  change_qty: number;
  close_vial: number | null;
  created_by: number | null;
  createdAt: Generated<Date>;
  customer_id: number | null;
  customerCode: string | null;
  deleted_at: Date | null;
  device_type: Generated<number>;
  dose_1: number | null;
  dose_2: number | null;
  entity_id: number;
  id: Generated<number>;
  master_material_id: number | null;
  material_id: number | null;
  open_vial: number | null;
  opening_qty: number;
  order_id: number | null;
  other_reason: string | null;
  patient_id: number | null;
  stock_id: number;
  transaction_reason_id: number | null;
  transaction_type_id: number;
  updated_by: number | null;
  updatedAt: Generated<Date>;
  vaccine_sequence: number | null;
  vendor_id: number | null;
}

export interface TransactionTypes {
  chg_type: Generated<number>;
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  title: string | null;
  title_en: string | null;
  updatedAt: Generated<Date>;
}

export interface UpdateStocks {
  createdAt: Date;
  date_cutoff: Date;
  deletedAt: Date | null;
  id: Generated<number>;
  master_material_id: number | null;
  province_id: number | null;
  qty: number;
  regency_id: number | null;
  stocks: string | null;
  updatedAt: Date | null;
}

export interface UserChgHistories {
  created_at: Generated<Date>;
  id: Generated<number>;
  new_values: string;
  old_values: string | null;
  updated_at: Generated<Date>;
  updated_by: string;
  user_id: number;
}

export interface Users {
  address: string | null;
  application_version: string | null;
  change_password: Generated<number | null>;
  created_at: Generated<Date>;
  created_by: number | null;
  date_of_birth: Date | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  email: string | null;
  entity_id: number | null;
  fcm_token: string | null;
  firstname: string | null;
  gender: number | null;
  global_id: number | null;
  id: Generated<number>;
  imei_number: string | null;
  iota_app_gui_theme: string | null;
  last_device: number | null;
  last_login: Date | null;
  last_mobile_access: Date | null;
  lastname: string | null;
  manufacture_id: number | null;
  mobile_phone: string | null;
  mobile_phone_2: string | null;
  mobile_phone_brand: string | null;
  mobile_phone_model: string | null;
  password: string | null;
  permission: string | null;
  role: number | null;
  sim_id: string | null;
  sim_provider: string | null;
  status: Generated<number | null>;
  timezone_id: number | null;
  token_login: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  username: string | null;
  view_only: Generated<number>;
  village_id: string | null;
  ws_global_id: number | null;
}

export interface UserTags {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: Generated<number>;
  title: string | null;
  updated_at: Generated<Date>;
}

export interface UserUserTags {
  created_at: Generated<Date>;
  id: Generated<number>;
  updated_at: Generated<Date>;
  user_id: number | null;
  user_tag_id: number | null;
}

export interface ViewDashboard {
  created_date: Generated<number>;
  distributed_qty: number | null;
  entity_name: Generated<number>;
  issued_qty: number | null;
  material_id: Generated<number>;
  material_name: Generated<number>;
  province_id: Generated<number>;
  province_name: Generated<number>;
  received_qty: number | null;
  regency_id: Generated<number>;
  regency_name: Generated<number>;
  sub_district_id: Generated<number>;
  sub_district_name: Generated<number>;
}

export interface ViewEntitiesRegion {
  created_at: Generated<Date>;
  district_id: number;
  entities_id: number;
  entities_name: number;
  is_vendor: number;
  province_id: number;
  province_name: number;
  regency_id: number;
  regency_name: number;
  subdistrict_name: number;
  updated_at: Generated<Date>;
}

export interface ViewOrderDashboard {
  created_at: Generated<Date>;
  created_date: number;
  distributed_qty: number;
  entity_name: number;
  id: number;
  material_id: number;
  material_name: number;
  province_id: number;
  province_name: number;
  received_qty: number;
  regency_id: number;
  regency_name: number;
  sub_district_id: number;
  sub_district_name: number;
  updated_at: Generated<Date>;
}

export interface ViewOrderFulfilled {
  created_at: Generated<Date>;
  created_date: number;
  entity_id: number;
  entity_name: number;
  id: number;
  material_id: number;
  material_name: number;
  province_id: number;
  province_name: number;
  qty: number;
  regency_id: number;
  regency_name: number;
  sub_district_id: number;
  sub_district_name: number;
  updated_at: Generated<Date>;
}

export interface ViewOrderShipped {
  created_at: Generated<Date>;
  created_date: number;
  entity_id: number;
  entity_name: number;
  id: number;
  material_id: number;
  material_name: number;
  province_id: number;
  province_name: number;
  qty: number;
  regency_id: number;
  regency_name: number;
  sub_district_id: number;
  sub_district_name: number;
  updated_at: Generated<Date>;
}

export interface ViewOrderStocks {
  allocated_qty: number;
  created_at: Generated<Date>;
  created_by: number;
  deleted_at: number;
  deleted_by: number;
  entity_id: number;
  fulfill_reason: number;
  id: number;
  order_id: number;
  order_item_id: number;
  ordered_qty: number;
  other_reason: number;
  qrcode: number;
  received_qty: number;
  status: number;
  stock_id: number;
  updated_at: Generated<Date>;
  updated_by: number;
}

export interface ViewRegion {
  created_at: Generated<Date>;
  province_id: number;
  province_name: number;
  regency_id: number;
  regency_name: number;
  subdistrict_id: number;
  subdistrict_name: number;
  updated_at: Generated<Date>;
}

export interface ViewTransIssue {
  created_at: Generated<Date>;
  created_date: number;
  entity_id: number;
  entity_name: number;
  id: number;
  material_id: number;
  material_name: number;
  province_id: number;
  province_name: number;
  qty: number;
  regency_id: number;
  regency_name: number;
  sub_district_id: number;
  sub_district_name: number;
  updated_at: Generated<Date>;
}

export interface Villages {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  name: string | null;
  sub_district_id: string | null;
  sub_district_id_new: string | null;
  sub_district_id_old: string | null;
  updated_at: Generated<Date>;
  village_id_new: string | null;
  village_id_old: string | null;
}

export interface VillagesBackup {
  created_at: Generated<Date>;
  deleted_at: Date | null;
  id: string;
  name: string | null;
  sub_district_id: string | null;
  updated_at: Generated<Date>;
}

export interface YearlyChild {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_id: number;
  id: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
  yearly_plan_id: number | null;
}

export interface YearlyChildHasIpvs {
  created_at: Generated<Date>;
  created_by: number | null;
  custom_ipv: Generated<Decimal>;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  master_ipv_id: number;
  status: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  yearly_child_id: number;
}

export interface YearlyChildHasResults {
  activity_id: number | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  ipv: Generated<Decimal>;
  master_material_id: number | null;
  material_id: number;
  monthly_distribution: Generated<string>;
  monthly_need: number | null;
  monthly_vial: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  version: Generated<number>;
  weekly_need: number | null;
  weekly_vial: number | null;
  yearly_child_id: number;
  yearly_need: Generated<number>;
  yearly_vial: number | null;
}

export interface YearlyChildHasTarget {
  created_at: Generated<Date>;
  custom_qty: Generated<number>;
  deleted_at: Date | null;
  id: Generated<number>;
  master_target_id: number;
  propotion: Generated<Decimal>;
  qty: Generated<number>;
  status: string | null;
  updated_at: Generated<Date>;
  yearly_child_id: number;
}

export interface YearlyFormStep {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  province_id: number;
  regency_id: number;
  step: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: number | null;
  year: string;
}

export interface YearlyParent {
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  province_id: number;
  regency_id: number;
  updated_at: Generated<Date>;
  updated_by: number | null;
  year: string;
}

export interface YearlyParentHasTarget {
  created_at: Generated<Date>;
  custom_qty: number | null;
  deleted_at: Date | null;
  id: Generated<number>;
  master_target_id: number;
  propotion: Generated<Decimal>;
  qty: number | null;
  status: string | null;
  updated_at: Generated<Date>;
  yearly_plan_id: number | null;
}

export interface YearlyPlanHasIpvs {
  created_at: Generated<Date>;
  created_by: number | null;
  custom_ipv: Generated<Decimal>;
  deleted_at: Date | null;
  deleted_by: number | null;
  id: Generated<number>;
  master_ipv_id: number;
  status: string | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  yearly_plan_id: number;
}

export interface YearlyPlans {
  comment: string | null;
  created_at: Generated<Date>;
  created_by: number | null;
  deleted_at: Date | null;
  deleted_by: number | null;
  entity_regency_id: number;
  id: Generated<number>;
  status: string | null;
  step: Generated<number>;
  submitted_at: Date | null;
  submitted_by: number | null;
  updated_at: Generated<Date>;
  updated_by: number | null;
  year: string;
}

export interface YearlyStockProvince {
  consumption: number | null;
  createdAt: Generated<Date>;
  deletedAt: Date | null;
  id: Generated<number>;
  master_material_id: number;
  province_id: number;
  qty: number;
  updatedAt: Generated<Date>;
  year: number;
}

export interface DB {
  asset_models: AssetModels;
  asset_types: AssetTypes;
  assets: Assets;
  batches: Batches;
  biofarma_orders: BiofarmaOrders;
  biofarma_orders_copy: BiofarmaOrdersCopy;
  biofarma_smdv_orders: BiofarmaSmdvOrders;
  coldchain_capacity_equipment_unused: ColdchainCapacityEquipmentUnused;
  coldstorage_annual_planning: ColdstorageAnnualPlanning;
  coldstorage_annual_planning_temperature: ColdstorageAnnualPlanningTemperature;
  coldstorage_materials: ColdstorageMaterials;
  coldstorage_per_temperature: ColdstoragePerTemperature;
  coldstorage_transaction_logs: ColdstorageTransactionLogs;
  coldstorages: Coldstorages;
  commitment_items: CommitmentItems;
  commitments: Commitments;
  configurations: Configurations;
  contracts: Contracts;
  customer_has_activities: CustomerHasActivities;
  customer_vendors: CustomerVendors;
  customer_vendors_11feb: CustomerVendors11feb;
  customer_vendors_13feb1105: CustomerVendors13feb1105;
  customer_vendors_3feb21: CustomerVendors3feb21;
  customer_vendors_backup_30_734: CustomerVendorsBackup30734;
  customer_vendors28Juli21: CustomerVendors28Juli21;
  dashboard_satusehat: DashboardSatusehat;
  delete_biofarma: DeleteBiofarma;
  din_order_items: DinOrderItems;
  din_orders: DinOrders;
  download_logs: DownloadLogs;
  dummy_biofarma: DummyBiofarma;
  entities: Entities;
  entity_activity_date: EntityActivityDate;
  entity_entity_tags: EntityEntityTags;
  entity_has_master_materials: EntityHasMasterMaterials;
  entity_master_material_activities: EntityMasterMaterialActivities;
  entity_master_material_minmax: EntityMasterMaterialMinmax;
  entity_tags: EntityTags;
  entity_tags_old: EntityTagsOld;
  event_report_child_reasons: EventReportChildReasons;
  event_report_comments: EventReportComments;
  event_report_histories: EventReportHistories;
  event_report_items: EventReportItems;
  event_report_reasons: EventReportReasons;
  event_reports: EventReports;
  extermination_flow_reasons: ExterminationFlowReasons;
  extermination_flows: ExterminationFlows;
  extermination_transaction_types: ExterminationTransactionTypes;
  extermination_transactions: ExterminationTransactions;
  integration_asik_aggregate: IntegrationAsikAggregate;
  integration_ayo_sehat: IntegrationAyoSehat;
  integration_emonev_materials: IntegrationEmonevMaterials;
  integration_emonev_provinces: IntegrationEmonevProvinces;
  integration_emonev_regencies: IntegrationEmonevRegencies;
  integration_order_items: IntegrationOrderItems;
  integration_order_items_kfa: IntegrationOrderItemsKfa;
  integration_orders: IntegrationOrders;
  inventory_overviews: InventoryOverviews;
  kfa_levels: KfaLevels;
  log_entity_material_imports: LogEntityMaterialImports;
  login_attempts: LoginAttempts;
  manufacture_types: ManufactureTypes;
  manufactures: Manufactures;
  mapping_cancel_discard: MappingCancelDiscard;
  mapping_entities: MappingEntities;
  mapping_master_materials: MappingMasterMaterials;
  master_activities: MasterActivities;
  master_ipvs: MasterIpvs;
  master_ipvs_copy: MasterIpvsCopy;
  master_kode_wilayah: MasterKodeWilayah;
  master_material_has_activities: MasterMaterialHasActivities;
  master_material_has_companions: MasterMaterialHasCompanions;
  master_material_has_conditions: MasterMaterialHasConditions;
  master_material_has_manufactures: MasterMaterialHasManufactures;
  master_material_type: MasterMaterialType;
  master_materials: MasterMaterials;
  master_target: MasterTarget;
  master_target_distributions: MasterTargetDistributions;
  master_target_regencies: MasterTargetRegencies;
  master_volume_material_manufactures: MasterVolumeMaterialManufactures;
  material_categories: MaterialCategories;
  material_companions: MaterialCompanions;
  material_conditions: MaterialConditions;
  material_entity: MaterialEntity;
  material_manufacture: MaterialManufacture;
  material_material_categories: MaterialMaterialCategories;
  material_material_tag: MaterialMaterialTag;
  material_tags: MaterialTags;
  materials: Materials;
  materialss: Materialss;
  new_opname_items: NewOpnameItems;
  new_opname_stocks: NewOpnameStocks;
  new_opnames: NewOpnames;
  notification_types: NotificationTypes;
  opname_actions: OpnameActions;
  opname_item_reason_actions: OpnameItemReasonActions;
  opname_period: OpnamePeriod;
  opname_reasons: OpnameReasons;
  opname_stock_items: OpnameStockItems;
  opname_stocks: OpnameStocks;
  order_comments: OrderComments;
  order_histories: OrderHistories;
  order_item_projection_capacities: OrderItemProjectionCapacities;
  order_items: OrderItems;
  order_items_kfa: OrderItemsKfa;
  order_order_tag: OrderOrderTag;
  order_reports: OrderReports;
  order_stock_exterminations: OrderStockExterminations;
  order_stock_purchase: OrderStockPurchase;
  order_stocks: OrderStocks;
  order_tags: OrderTags;
  orders: Orders;
  patients: Patients;
  pieces_purchase: PiecesPurchase;
  provinces: Provinces;
  rabies_vaccine_rules: RabiesVaccineRules;
  range_temperature: RangeTemperature;
  reconciliation: Reconciliation;
  reconciliation_item_reason_actions: ReconciliationItemReasonActions;
  reconciliation_items: ReconciliationItems;
  regencies: Regencies;
  regencies_backup: RegenciesBackup;
  region_conversion_province: RegionConversionProvince;
  region_conversion_regencies: RegionConversionRegencies;
  region_conversion_subdistricts: RegionConversionSubdistricts;
  region_conversion_villages: RegionConversionVillages;
  regions: Regions;
  request_order_items: RequestOrderItems;
  request_orders: RequestOrders;
  reset_passwords: ResetPasswords;
  roles: Roles;
  SequelizeMeta: SequelizeMeta;
  service_types: ServiceTypes;
  source_materials: SourceMaterials;
  stock_exterminations: StockExterminations;
  stock_intervals: StockIntervals;
  stocks: Stocks;
  stop_notification_histories: StopNotificationHistories;
  stop_notification_reasons: StopNotificationReasons;
  sub_districts: SubDistricts;
  sub_districts_backup: SubDistrictsBackup;
  timezones: Timezones;
  track_devices: TrackDevices;
  tracking_log_eg: TrackingLogEg;
  transaction_injections: TransactionInjections;
  transaction_items: TransactionItems;
  transaction_logs: TransactionLogs;
  transaction_patients: TransactionPatients;
  transaction_purchase: TransactionPurchase;
  transaction_reasons: TransactionReasons;
  transaction_types: TransactionTypes;
  transactions: Transactions;
  transactions_13122022: Transactions13122022;
  transactions_last_3months: TransactionsLast3months;
  update_stocks: UpdateStocks;
  user_chg_histories: UserChgHistories;
  user_tags: UserTags;
  user_user_tags: UserUserTags;
  users: Users;
  view_dashboard: ViewDashboard;
  view_entities_region: ViewEntitiesRegion;
  view_order_dashboard: ViewOrderDashboard;
  view_order_fulfilled: ViewOrderFulfilled;
  view_order_shipped: ViewOrderShipped;
  view_order_stocks: ViewOrderStocks;
  view_region: ViewRegion;
  view_trans_issue: ViewTransIssue;
  villages: Villages;
  villages_backup: VillagesBackup;
  yearly_child: YearlyChild;
  yearly_child_has_ipvs: YearlyChildHasIpvs;
  yearly_child_has_results: YearlyChildHasResults;
  yearly_child_has_target: YearlyChildHasTarget;
  yearly_form_step: YearlyFormStep;
  yearly_parent: YearlyParent;
  yearly_parent_has_target: YearlyParentHasTarget;
  yearly_plan_has_ipvs: YearlyPlanHasIpvs;
  yearly_plans: YearlyPlans;
  yearly_stock_province: YearlyStockProvince;
}
