export const TRANSACTION_TYPE = {
  STOCK_COUNT: 1,
  ISSUES: 2,
  RECEIPTS: 3,
  DISCARDS: 4,
  RETURN: 5,
  RECEIPT_OPEN_VIAL: 6,
  ADD_STOCK: 7,
  REMOVE_STOCK: 8,
  CANCEL_DISCARD: 9,
  CONSUMPTION: 10,
  TRANSFER_STOCK: 11,
}
