import { db } from "@/scripts/db.platform.js"
import { sql } from "kysely"

export const populateRolesToResourceMapping = async () => {
  console.info("populate roles_to_resource_mapping start...")

  await db.transaction().execute(async (trx) => {
    // Truncate the table
    await trx.executeQuery(
      sql`truncate table roles_to_resource_mapping`.compile(db)
    )

    // Insert rows
    await trx
      .insertInto("roles_to_resource_mapping")
      .values([
        {
          id: 14,
          http_method: "get",
          route_handler: "/core/entities",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-25T09:05:41"),
          updated_at: new Date("2025-03-05T04:02:15"),
          created_by: "admin",
          updated_by: null,
        },
        {
          id: 15,
          http_method: "post",
          route_handler: "/core/entities",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-25T09:06:42"),
          updated_at: new Date("2025-02-27T10:30:14"),
          created_by: "admin",
          updated_by: null,
        },
        {
          id: 16,
          http_method: "GET",
          route_handler: "/core/entities/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-25T09:26:11"),
          updated_at: new Date("2025-03-05T04:01:41"),
          created_by: "admin",
          updated_by: null,
        },
        {
          id: 17,
          http_method: "get",
          route_handler: "/core/users/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-25T14:42:47"),
          updated_at: new Date("2025-08-06T07:07:14"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 18,
          http_method: "get",
          route_handler: "/core/users/xls-template",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-25T14:42:47"),
          updated_at: new Date("2025-02-27T09:31:45"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 19,
          http_method: "GET",
          route_handler: "/core/users/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-08-06T07:07:14"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 20,
          http_method: "GET",
          route_handler: "/core/users/xls-template",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:30:26"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 21,
          http_method: "POST",
          route_handler: "/core/auth/login",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:53:06"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 22,
          http_method: "POST",
          route_handler: "/core/account/logout",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:52:43"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 23,
          http_method: "POST",
          route_handler: "/core/account/forgot-password",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:30:26"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 24,
          http_method: "GET",
          route_handler: "/core/account/profile",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:50:45"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 25,
          http_method: "GET",
          route_handler: "/core/users/:id/chg_history",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T11:03:07"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 26,
          http_method: "PUT",
          route_handler: "/core/users/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:54:27"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 27,
          http_method: "POST",
          route_handler: "/core/account/update-password",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T04:06:01"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 28,
          http_method: "GET",
          route_handler: "/core/account/workspaces",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 29,
          http_method: "PUT",
          route_handler: "/core/account/workspaces",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 30,
          http_method: "GET",
          route_handler: "/core/users",
          role_list:
            "super admin, admin, manager, operator, super admin external",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-08-06T06:53:53"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 31,
          http_method: "GET",
          route_handler: "/core/users/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T11:01:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 32,
          http_method: "POST",
          route_handler: "/core/users/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:30:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 33,
          http_method: "POST",
          route_handler: "/core/users",
          role_list: "super admin, admin, super admin external",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-05-07T09:24:48"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 34,
          http_method: "PUT",
          route_handler: "/core/users/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T11:02:02"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 35,
          http_method: "PUT",
          route_handler: "/core/users/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:09:16"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 36,
          http_method: "GET",
          route_handler: "/core/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:41"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 37,
          http_method: "GET",
          route_handler: "/core/materials/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:41"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 38,
          http_method: "GET",
          route_handler: "/core/materials/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:41"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 39,
          http_method: "POST",
          route_handler: "/core/materials/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:16:18"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 40,
          http_method: "POST",
          route_handler: "/core/materials",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:16:18"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 41,
          http_method: "PUT",
          route_handler: "/core/materials/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:16:18"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 42,
          http_method: "PUT",
          route_handler: "/core/materials/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:16:18"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 43,
          http_method: "GET",
          route_handler: "/core/materials/xls-template",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:41"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 44,
          http_method: "get",
          route_handler: "/core/manufactures",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 45,
          http_method: "get",
          route_handler: "/core/manufactures/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 46,
          http_method: "GET",
          route_handler: "/core/manufactures/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 47,
          http_method: "POST",
          route_handler: "/core/manufactures/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:18:04"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 48,
          http_method: "GET",
          route_handler: "/core/manufactures/xls-template",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 49,
          http_method: "POST",
          route_handler: "/core/manufactures",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:18:04"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 50,
          http_method: "PUT",
          route_handler: "/core/manufactures/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:18:04"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 51,
          http_method: "GET",
          route_handler: "/core/budget-sources",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 52,
          http_method: "GET",
          route_handler: "/core/budget-sources/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 53,
          http_method: "GET",
          route_handler: "/core/budget-sources/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 54,
          http_method: "POST",
          route_handler: "/core/budget-sources",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:14:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 55,
          http_method: "PUT",
          route_handler: "/core/budget-sources/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:14:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 56,
          http_method: "DELETE",
          route_handler: "/core/budget-sources/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T10:14:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 57,
          http_method: "GET",
          route_handler: "/main/users",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 58,
          http_method: "GET",
          route_handler: "/main/users/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 67,
          http_method: "GET",
          route_handler: "/main/entities",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 68,
          http_method: "GET",
          route_handler: "/main/entities/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 69,
          http_method: "GET",
          route_handler: "/main/entities/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 70,
          http_method: "PUT",
          route_handler: "/main/entities/:id/status/vendors",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 71,
          http_method: "GET",
          route_handler: "/main/entities/:id/users",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 72,
          http_method: "POST",
          route_handler: "/main/entities/:id/customers/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 73,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/xls-template",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 74,
          http_method: "DELETE",
          route_handler: "/main/entities/customers",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 75,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 76,
          http_method: "PUT",
          route_handler: "/main/entities/customers",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 77,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 79,
          http_method: "PUT",
          route_handler: "/main/entities/customers",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 80,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 81,
          http_method: "GET",
          route_handler: "/main/entities/:id/vendors",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 82,
          http_method: "GET",
          route_handler: "/main/entities/:id/activities",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 83,
          http_method: "POST",
          route_handler: "/main/entities/activities/submit-time",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 84,
          http_method: "GET",
          route_handler: "/main/entities/:entity_id/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 85,
          http_method: "POST",
          route_handler: "/main/entities/:entity_id/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 86,
          http_method: "PUT",
          route_handler: "/main/entities/:entity_id/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:30"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 87,
          http_method: "DELETE",
          route_handler:
            "/main/entities/:entity_id/materials/:entity_master_material_activities_id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 88,
          http_method: "GET",
          route_handler: "/main/entities-materials-bulk",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 89,
          http_method: "POST",
          route_handler: "/main/entities-materials-bulk/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 90,
          http_method: "GET",
          route_handler: "/main/entities-materials-bulk/template",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 91,
          http_method: "PUT",
          route_handler: "/main/entities/:id/status",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 92,
          http_method: "GET",
          route_handler: "/main/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 93,
          http_method: "GET",
          route_handler: "/main/materials/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 94,
          http_method: "GET",
          route_handler: "/main/materials/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 95,
          http_method: "POST",
          route_handler: "/main/materials/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 96,
          http_method: "PUT",
          route_handler: "/main/materials/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 97,
          http_method: "GET",
          route_handler: "/main/materials",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 98,
          http_method: "GET",
          route_handler: "/main/materials/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 99,
          http_method: "GET",
          route_handler: "/main/materials/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 100,
          http_method: "POST",
          route_handler: "/main/materials/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 101,
          http_method: "PUT",
          route_handler: "/main/materials/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 102,
          http_method: "GET",
          route_handler: "/main/manufactures",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 103,
          http_method: "GET",
          route_handler: "/main/manufactures/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 104,
          http_method: "GET",
          route_handler: "/main/budget-sources",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 105,
          http_method: "GET",
          route_handler: "/main/budget-sources/:id",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 106,
          http_method: "GET",
          route_handler: "/main/budget-sources/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:53:49"),
          updated_at: new Date("2025-03-01T04:31:31"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 107,
          http_method: "GET",
          route_handler: "/core/entities/xls",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T10:47:25"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 108,
          http_method: "get",
          route_handler: "/core/material-types",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T10:57:21"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 109,
          http_method: "get",
          route_handler: "/core/workspaces",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T11:00:39"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 110,
          http_method: "GET",
          route_handler: "/core/master/provinces",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 111,
          http_method: "GET",
          route_handler: "/core/master/regencies",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 112,
          http_method: "GET",
          route_handler: "/core/entity-types",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 113,
          http_method: "GET",
          route_handler: "/core/entity-tags",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 114,
          http_method: "GET",
          route_handler: "/core/master/subdistricts",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 115,
          http_method: "GET",
          route_handler: "/core/master/villages",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-26T10:51:46"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 116,
          http_method: "GET",
          route_handler: "/core/manufactures/type",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-26T04:46:54"),
          updated_at: new Date("2025-02-27T01:30:52"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 117,
          http_method: "GET",
          route_handler: "/core/materials/:id/relation",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T06:57:07"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 118,
          http_method: "POST",
          route_handler: "/core/users/update-last-login",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T07:40:05"),
          updated_at: new Date("2025-02-27T07:40:05"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 119,
          http_method: "PUT",
          route_handler: "/core/entities/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T09:17:16"),
          updated_at: new Date("2025-02-27T10:52:08"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 120,
          http_method: "POST",
          route_handler: "/core/entities/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T10:54:48"),
          updated_at: new Date("2025-02-27T10:54:48"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 121,
          http_method: "GET",
          route_handler: "/core/entities/xls-template",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T10:55:33"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 122,
          http_method: "DELETE",
          route_handler: "/core/manufactures/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T11:12:40"),
          updated_at: new Date("2025-02-27T11:12:40"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 124,
          http_method: "GET",
          route_handler: "/core/material-relations",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T11:15:43"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 125,
          http_method: "GET",
          route_handler: "/core/material-levels",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T11:16:51"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 126,
          http_method: "GET",
          route_handler: "/core/material-units",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-02-27T11:18:54"),
          updated_at: new Date("2025-03-05T04:01:42"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 127,
          http_method: "GET",
          route_handler: "/main/users/:id/chg_history",
          role_list: "PUBLIC",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-03-04T05:13:06"),
          updated_at: new Date("2025-03-04T05:13:06"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 128,
          http_method: "POST",
          route_handler: "/core/programs",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-21T16:35:29"),
          updated_at: new Date("2025-04-21T16:35:16"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 129,
          http_method: "GET",
          route_handler: "/core/programs",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-21T16:34:55"),
          updated_at: new Date("2025-07-04T04:00:56"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 130,
          http_method: "GET",
          route_handler: "/core/programs/:id",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-21T16:34:55"),
          updated_at: new Date("2025-04-21T16:35:07"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 131,
          http_method: "PUT",
          route_handler: "/core/programs/:id",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-21T16:34:55"),
          updated_at: new Date("2025-04-21T16:35:07"),
          created_by: "super admin",
          updated_by: null,
        },
        {
          id: 132,
          http_method: "POST",
          route_handler: "/core/programs/:id/activities",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 133,
          http_method: "GET",
          route_handler: "/core/programs/:id/activities",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 134,
          http_method: "GET",
          route_handler: "/core/programs/:id/activities/:id",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 135,
          http_method: "PUT",
          route_handler: "/core/programs/:id/activities/:id",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 136,
          http_method: "PUT",
          route_handler: "/core/programs/:id/activities/:id/status",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 137,
          http_method: "GET",
          route_handler: "/core/programs/:id/activities/xls",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 138,
          http_method: "GET",
          route_handler: "/core/programs/:id/activities/xls-template",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 139,
          http_method: "POST",
          route_handler: "/core/programs/:id/activities/xls",
          role_list: "super admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-28T10:33:31"),
          updated_at: new Date("2025-04-28T10:33:31"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 140,
          http_method: "POST",
          route_handler: "/main/activities",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 141,
          http_method: "GET",
          route_handler: "/main/activities",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T16:12:09"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 142,
          http_method: "GET",
          route_handler: "/main/activities/:id",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T16:12:09"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 143,
          http_method: "PUT",
          route_handler: "/main/activities/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 144,
          http_method: "PUT",
          route_handler: "/main/activities/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 145,
          http_method: "GET",
          route_handler: "/main/activities/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 146,
          http_method: "GET",
          route_handler: "/main/activities/xls-template",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 147,
          http_method: "POST",
          route_handler: "/main/activities/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 148,
          http_method: "PUT",
          route_handler: "/main/manufactures/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 149,
          http_method: "PUT",
          route_handler: "/main/budget-sources/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-04-30T04:38:03"),
          updated_at: new Date("2025-04-30T04:38:03"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 150,
          http_method: "GET",
          route_handler: "/main/stock-opname-periods",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-07-23T06:17:49"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 151,
          http_method: "POST",
          route_handler: "/main/stock-opname-periods",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:53"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 152,
          http_method: "PUT",
          route_handler: "/main/stock-opname-periods/:id",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:53"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 153,
          http_method: "PATCH",
          route_handler: "/main/stock-opname-periods/:id/status",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:53"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 154,
          http_method: "GET",
          route_handler: "/main/stock-opname-periods/:id",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:53"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 155,
          http_method: "GET",
          route_handler: "/main/stock-opnames",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:53"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 156,
          http_method: "POST",
          route_handler: "/main/stock-opnames",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:54"),
          created_by: "30569",
          updated_by: null,
        },
        {
          id: 157,
          http_method: "GET",
          route_handler: "/main/stock-opnames/xls",
          role_list: "super admin, admin, manager",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-06-10T02:53:24"),
          updated_at: new Date("2025-06-10T03:02:54"),
          created_by: "30569",
          updated_by: null,
        },
        // New routes added from allow() function migration
        {
          id: 158,
          http_method: "GET",
          route_handler: "/main/entities/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 159,
          http_method: "PUT",
          route_handler: "/main/entities/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 160,
          http_method: "PUT",
          route_handler: "/main/entities/:id/status/vendors",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 161,
          http_method: "GET",
          route_handler: "/main/entities/:id",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 162,
          http_method: "GET",
          route_handler: "/main/entities",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 163,
          http_method: "GET",
          route_handler: "/main/materials",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 164,
          http_method: "GET",
          route_handler: "/main/materials/xls",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 165,
          http_method: "GET",
          route_handler: "/main/materials/xls-template",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 166,
          http_method: "GET",
          route_handler: "/main/materials/:id",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 167,
          http_method: "POST",
          route_handler: "/main/materials/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 168,
          http_method: "PUT",
          route_handler: "/main/materials/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 169,
          http_method: "PUT",
          route_handler: "/main/materials/:id/status",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 170,
          http_method: "DELETE",
          route_handler: "/main/entities/customers",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 171,
          http_method: "PUT",
          route_handler: "/main/entities/customers",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 172,
          http_method: "POST",
          route_handler: "/main/entities/customers",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 173,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/list-relation-customers",
          role_list: "super admin, admin, manager, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 174,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/xls-template",
          role_list: "super admin, admin, manager, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 175,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers/xls",
          role_list: "super admin, admin, manager, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 176,
          http_method: "POST",
          route_handler: "/main/entities/:id/customers/xls",
          role_list: "super admin, admin, manager, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 177,
          http_method: "GET",
          route_handler: "/main/entities/:id/customers",
          role_list: "super admin, admin, manager, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 178,
          http_method: "POST",
          route_handler: "/main/entities/activities/submit-time",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 179,
          http_method: "GET",
          route_handler: "/main/entities/:id/activities",
          role_list: "super admin, admin, manager, operator, vendor iot",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 180,
          http_method: "GET",
          route_handler: "/main/stocks",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 181,
          http_method: "GET",
          route_handler: "/main/stocks/entities",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 182,
          http_method: "GET",
          route_handler: "/main/stocks/details",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 183,
          http_method: "GET",
          route_handler: "/main/stocks/xls",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 184,
          http_method: "POST",
          route_handler: "/main/entities-materials-bulk/xls",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 185,
          http_method: "GET",
          route_handler: "/main/entities-materials-bulk/template",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 186,
          http_method: "GET",
          route_handler: "/main/entities-materials-bulk",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 187,
          http_method: "POST",
          route_handler: "/main/entities/:id/materials",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 188,
          http_method: "DELETE",
          route_handler: "/main/entities/:id/materials/:id",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 189,
          http_method: "PUT",
          route_handler: "/main/entities/:id/materials",
          role_list: "super admin, admin",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 190,
          http_method: "GET",
          route_handler: "/main/disposal-stocks/stock",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 191,
          http_method: "GET",
          route_handler: "/main/disposal-stocks/stock/xls",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 192,
          http_method: "GET",
          route_handler: "/main/disposal-stocks/stocks/detail",
          role_list: "super admin, admin, manager, operator",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 193,
          http_method: "GET",
          route_handler: "/main/ssl/transactions",
          role_list: "Third Party",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
        {
          id: 194,
          http_method: "GET",
          route_handler: "/main/ssl/stock-opnames",
          role_list: "Third Party",
          resource_type: "be",
          status: 1,
          created_at: new Date("2025-08-20T06:36:00"),
          updated_at: new Date("2025-08-20T06:36:00"),
          created_by: "migration",
          updated_by: null,
        },
      ])
      .execute()
  })
  console.log("populate roles_to_resource_mapping finished")
  process.exit(0)
}
