import { db } from "@/scripts/db.platform.js"
import { sql } from "kysely"

export const populateTransactionTypes = async () => {
  console.info("populate start...")

  await db.transaction().execute(async (trx) => {
    // Truncate the table
    await trx.executeQuery(sql`truncate table ws_transaction_types`.compile(db))

    // Insert rows
    await trx
      .insertInto("ws_transaction_types")
      .values([
        {
          id: 1,
          title: "Stock Count",
          title_en: "Stock Count",
          change_type: "2",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: new Date("2025-08-01T13:42:52"),
          enable: 0,
          sequence: null,
        },
        {
          id: 2,
          title: "Pengeluaran",
          title_en: "Issue",
          change_type: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 0,
          sequence: null,
        },
        {
          id: 3,
          title: "Penerimaan",
          title_en: "Receive",
          change_type: "1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 0,
          sequence: null,
        },
        {
          id: 4,
          title: "Pembuangan",
          title_en: "Discard",
          change_type: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 1,
          sequence: 5,
        },
        {
          id: 5,
          title: "Pengembalian Faskes",
          title_en: "Return of Health Facilities",
          change_type: "1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 1,
          sequence: 4,
        },
        {
          id: 6,
          title: "Penerimaan Vial Terbuka",
          title_en: "Open Vial Acceptance",
          change_type: "1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: new Date("2025-08-01T13:42:52"),
          enable: 0,
          sequence: null,
        },
        {
          id: 7,
          title: "Add Stock",
          title_en: "Add Stock",
          change_type: "1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 1,
          sequence: 1,
        },
        {
          id: 8,
          title: "Remove Stock",
          title_en: "Remove Stock",
          change_type: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 1,
          sequence: 2,
        },
        {
          id: 9,
          title: "Pembatalan Pembuangan",
          title_en: "Cancellation of Discard",
          change_type: "1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-01-07T15:31:04"),
          updated_at: new Date("2025-01-07T15:31:04"),
          deleted_at: null,
          enable: 1,
          sequence: 6,
        },
        {
          id: 10,
          title: "Konsumsi",
          title_en: "Consumption",
          change_type: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-02-19T04:40:46"),
          updated_at: new Date("2025-02-19T04:40:46"),
          deleted_at: null,
          enable: 1,
          sequence: 3,
        },
        {
          id: 11,
          title: "Transfer Stok",
          title_en: "Transfer Stock",
          change_type: "4",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          created_at: new Date("2025-06-19T14:46:51"),
          updated_at: new Date("2025-06-19T14:46:51"),
          deleted_at: null,
          enable: 1,
          sequence: 7,
        },
      ])
      .execute()
  })
  console.log("populate finished")
  process.exit(0)
}
