/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AssetCommunicationProviders {
  created_at: Date;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  deleted_by: Generated<number | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  updated_at: Date;
  updated_by: Generated<number | null>;
}

export interface AssetElectricity {
  created_at: Date;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  deleted_by: Generated<number | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  updated_at: Date;
  updated_by: Generated<number | null>;
}

export interface AssetModel {
  capacity: Generated<number | null>;
  capacity_gross: Generated<number | null>;
  capacity_gross_2: Generated<number | null>;
  capacity_gross_3: Generated<number | null>;
  capacity_nett: Generated<number | null>;
  capacity_nett_2: Generated<number | null>;
  capacity_nett_3: Generated<number | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  only_logger: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface AssetRoles {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  is_open: Generated<number | null>;
  role: number;
  updated_at: Date;
}

export interface Assets {
  activity_duration: Generated<number | null>;
  activity_status: Generated<number | null>;
  activity_time: Generated<Date | null>;
  alarm_duration: Generated<number | null>;
  alarm_status: Generated<number | null>;
  alarm_type: Generated<number | null>;
  alarm_updated_at: Generated<Date | null>;
  asset_communication_provider_id: Generated<number | null>;
  asset_vendor_id: Generated<number | null>;
  battery: Generated<number | null>;
  borrowed_from: Generated<number | null>;
  budget_src: Generated<number | null>;
  budget_year: Generated<number | null>;
  calibration_schedule_id: Generated<number | null>;
  child_pos: Generated<number | null>;
  coldchain_capacity_equipment_id: Generated<number | null>;
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  deleted_reason: Generated<string | null>;
  device_code: Generated<number | null>;
  domain_name: Generated<string | null>;
  electricity_available_id: Generated<number | null>;
  entity_id: Generated<number>;
  id: Generated<number>;
  is_stock_opname: Generated<number | null>;
  last_calibration_date: Generated<Date | null>;
  last_maintenance_date: Generated<Date | null>;
  lat: Generated<number | null>;
  lng: Generated<number | null>;
  logger_status: Generated<string | null>;
  logger_status_id: Generated<number | null>;
  maintainer_id: Generated<number | null>;
  maintenance_schedule_id: Generated<number | null>;
  manufacture_id: Generated<number | null>;
  max_temp: Generated<number | null>;
  max_temp_2: Generated<number | null>;
  max_temp_3: Generated<number | null>;
  min_temp: Generated<number | null>;
  min_temp_2: Generated<number | null>;
  min_temp_3: Generated<number | null>;
  model_id: Generated<number | null>;
  name: Generated<string | null>;
  other_budget_src: Generated<string | null>;
  other_capacity_gross: Generated<number | null>;
  other_capacity_nett: Generated<number | null>;
  other_manufacture: Generated<string | null>;
  other_max_temp: Generated<number | null>;
  other_min_temp: Generated<number | null>;
  other_model_asset: Generated<string | null>;
  other_type_asset: Generated<string | null>;
  ownership_qty: Generated<number | null>;
  ownership_status: Generated<number | null>;
  parent_id: Generated<number | null>;
  power: Generated<number | null>;
  power_available: Generated<number | null>;
  power_updated_at: Generated<Date | null>;
  prod_year: Generated<string | null>;
  serial_number: string;
  signal: Generated<number | null>;
  status: Generated<number>;
  status_device: Generated<number>;
  temp: Generated<number | null>;
  type_id: Generated<number | null>;
  unused_reason_id: Generated<number | null>;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
  warranty_end_date: Generated<Date | null>;
  warranty_start_date: Generated<Date | null>;
  working_status: Generated<string | null>;
  working_status_id: Generated<number | null>;
}

export interface AssetStatus {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  is_coldstorage: Generated<number | null>;
  name: Generated<string | null>;
  name_en: Generated<string | null>;
  reason_type: Generated<number | null>;
  updated_at: Date;
}

export interface AssetStatuses {
  asset_id: Generated<number | null>;
  asset_maintainer_id: Generated<number | null>;
  asset_manufacture_id: Generated<number | null>;
  asset_manufacture_name: Generated<string | null>;
  asset_manufacture_production_year: Generated<number | null>;
  asset_model_capacity: Generated<number | null>;
  asset_model_id: Generated<number | null>;
  asset_model_name: Generated<string | null>;
  asset_prod_year: Generated<string | null>;
  asset_serial_number: Generated<string | null>;
  asset_type_id: Generated<number | null>;
  asset_type_name: Generated<string | null>;
  asset_working_status: Generated<string | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  entity_code: Generated<string | null>;
  entity_id: Generated<number | null>;
  entity_name: Generated<string | null>;
  entity_province_id: Generated<number | null>;
  entity_province_name: Generated<string | null>;
  entity_regency_id: Generated<number | null>;
  entity_regency_name: Generated<string | null>;
  entity_sub_district_id: Generated<number | null>;
  entity_sub_district_name: Generated<string | null>;
  entity_tag_id: Generated<number | null>;
  entity_tag_title: Generated<string | null>;
  entity_type: Generated<number | null>;
  entity_village_id: Generated<number | null>;
  entity_village_name: Generated<string | null>;
  excursion_from: Generated<string | null>;
  id: Generated<number>;
  logger_created_at: Generated<Date | null>;
  logger_deleted_at: Generated<Date | null>;
  logger_updated_at: Generated<Date | null>;
  parent_entity_code: Generated<string | null>;
  parent_entity_id: Generated<number | null>;
  parent_entity_name: Generated<string | null>;
  parent_entity_province_id: Generated<number | null>;
  parent_entity_province_name: Generated<string | null>;
  parent_entity_regency_id: Generated<number | null>;
  parent_entity_regency_name: Generated<string | null>;
  parent_entity_sub_district_id: Generated<number | null>;
  parent_entity_sub_district_name: Generated<string | null>;
  parent_entity_tag_id: Generated<number | null>;
  parent_entity_tag_title: Generated<string | null>;
  parent_entity_type: Generated<number | null>;
  parent_entity_village_id: Generated<number | null>;
  parent_entity_village_name: Generated<string | null>;
  parent_id: Generated<number | null>;
  parent_maintainer_firstname: Generated<string | null>;
  parent_maintainer_id: Generated<number | null>;
  parent_maintainer_lastname: Generated<string | null>;
  parent_maintainer_mobile_phone: Generated<string | null>;
  parent_manufacture_id: Generated<number | null>;
  parent_manufacture_name: Generated<string | null>;
  parent_model_capacity: Generated<number | null>;
  parent_model_id: Generated<number | null>;
  parent_model_name: Generated<string | null>;
  parent_prod_year: Generated<string | null>;
  parent_serial_number: Generated<string | null>;
  parent_type_id: Generated<number | null>;
  parent_type_name: Generated<string | null>;
  parent_working_status: Generated<string | null>;
  status: Generated<string | null>;
  temp: Generated<number | null>;
  updated_at: Generated<Date>;
}

export interface AssetStatusess {
  asset_id: Generated<number | null>;
  asset_maintainer_id: Generated<number | null>;
  asset_manufacture_id: Generated<number | null>;
  asset_manufacture_name: Generated<string | null>;
  asset_manufacture_production_year: Generated<number | null>;
  asset_model_capacity: Generated<number | null>;
  asset_model_id: Generated<number | null>;
  asset_model_name: Generated<string | null>;
  asset_prod_year: Generated<string | null>;
  asset_serial_number: Generated<string | null>;
  asset_type_id: Generated<number | null>;
  asset_type_name: Generated<string | null>;
  asset_working_status: Generated<string | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  entity_code: Generated<string | null>;
  entity_id: Generated<number | null>;
  entity_name: Generated<string | null>;
  entity_province_id: Generated<number | null>;
  entity_province_name: Generated<string | null>;
  entity_regency_id: Generated<number | null>;
  entity_regency_name: Generated<string | null>;
  entity_sub_district_id: Generated<number | null>;
  entity_sub_district_name: Generated<string | null>;
  entity_tag_id: Generated<number | null>;
  entity_tag_title: Generated<string | null>;
  entity_type: Generated<number | null>;
  entity_village_id: Generated<number | null>;
  entity_village_name: Generated<string | null>;
  excursion_from: Generated<string | null>;
  id: Generated<number>;
  logger_created_at: Generated<Date | null>;
  logger_deleted_at: Generated<Date | null>;
  logger_updated_at: Generated<Date | null>;
  parent_entity_code: Generated<string | null>;
  parent_entity_id: Generated<number | null>;
  parent_entity_name: Generated<string | null>;
  parent_entity_province_id: Generated<number | null>;
  parent_entity_province_name: Generated<string | null>;
  parent_entity_regency_id: Generated<number | null>;
  parent_entity_regency_name: Generated<string | null>;
  parent_entity_sub_district_id: Generated<number | null>;
  parent_entity_sub_district_name: Generated<string | null>;
  parent_entity_tag_id: Generated<number | null>;
  parent_entity_tag_title: Generated<string | null>;
  parent_entity_type: Generated<number | null>;
  parent_entity_village_id: Generated<number | null>;
  parent_entity_village_name: Generated<string | null>;
  parent_id: Generated<number | null>;
  parent_maintainer_firstname: Generated<string | null>;
  parent_maintainer_id: Generated<number | null>;
  parent_maintainer_lastname: Generated<string | null>;
  parent_maintainer_mobile_phone: Generated<string | null>;
  parent_manufacture_id: Generated<number | null>;
  parent_manufacture_name: Generated<string | null>;
  parent_model_capacity: Generated<number | null>;
  parent_model_id: Generated<number | null>;
  parent_model_name: Generated<string | null>;
  parent_prod_year: Generated<string | null>;
  parent_serial_number: Generated<string | null>;
  parent_type_id: Generated<number | null>;
  parent_type_name: Generated<string | null>;
  parent_working_status: Generated<string | null>;
  status: Generated<string | null>;
  temp: Generated<number | null>;
  updated_at: Generated<Date>;
}

export interface AssetStatusExcursions {
  asset_id: Generated<number | null>;
  asset_maintainer_id: Generated<number | null>;
  asset_manufacture_id: Generated<number | null>;
  asset_manufacture_name: Generated<string | null>;
  asset_manufacture_production_year: Generated<number | null>;
  asset_model_capacity: Generated<number | null>;
  asset_model_id: Generated<number | null>;
  asset_model_name: Generated<string | null>;
  asset_prod_year: Generated<string | null>;
  asset_serial_number: Generated<string | null>;
  asset_type_id: Generated<number | null>;
  asset_type_name: Generated<string | null>;
  asset_working_status: Generated<string | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  entity_code: Generated<string | null>;
  entity_id: Generated<number | null>;
  entity_name: Generated<string | null>;
  entity_province_id: Generated<number | null>;
  entity_province_name: Generated<string | null>;
  entity_regency_id: Generated<number | null>;
  entity_regency_name: Generated<string | null>;
  entity_sub_district_id: Generated<number | null>;
  entity_sub_district_name: Generated<string | null>;
  entity_tag_id: Generated<number | null>;
  entity_tag_title: Generated<string | null>;
  entity_type: Generated<number | null>;
  entity_village_id: Generated<number | null>;
  entity_village_name: Generated<string | null>;
  excursion_from: Generated<string | null>;
  id: Generated<number>;
  logger_created_at: Generated<Date | null>;
  logger_deleted_at: Generated<Date | null>;
  logger_updated_at: Generated<Date | null>;
  parent_entity_code: Generated<string | null>;
  parent_entity_id: Generated<number | null>;
  parent_entity_name: Generated<string | null>;
  parent_entity_province_id: Generated<number | null>;
  parent_entity_province_name: Generated<string | null>;
  parent_entity_regency_id: Generated<number | null>;
  parent_entity_regency_name: Generated<string | null>;
  parent_entity_sub_district_id: Generated<number | null>;
  parent_entity_sub_district_name: Generated<string | null>;
  parent_entity_tag_id: Generated<number | null>;
  parent_entity_tag_title: Generated<string | null>;
  parent_entity_type: Generated<number | null>;
  parent_entity_village_id: Generated<number | null>;
  parent_entity_village_name: Generated<string | null>;
  parent_id: Generated<number | null>;
  parent_maintainer_firstname: Generated<string | null>;
  parent_maintainer_id: Generated<number | null>;
  parent_maintainer_lastname: Generated<string | null>;
  parent_maintainer_mobile_phone: Generated<string | null>;
  parent_manufacture_id: Generated<number | null>;
  parent_manufacture_name: Generated<string | null>;
  parent_model_capacity: Generated<number | null>;
  parent_model_id: Generated<number | null>;
  parent_model_name: Generated<string | null>;
  parent_prod_year: Generated<string | null>;
  parent_serial_number: Generated<string | null>;
  parent_type_id: Generated<number | null>;
  parent_type_name: Generated<string | null>;
  parent_working_status: Generated<string | null>;
  status: Generated<string | null>;
  temp: Generated<number | null>;
  updated_at: Generated<Date>;
}

export interface AssetType {
  created_at: Generated<Date>;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  is_coldstorage: Generated<number | null>;
  is_electricity: Generated<number | null>;
  is_selection: Generated<number>;
  max_temp: Generated<number | null>;
  max_temp_2: Generated<number | null>;
  max_temp_3: Generated<number | null>;
  min_temp: Generated<number | null>;
  min_temp_2: Generated<number | null>;
  min_temp_3: Generated<number | null>;
  name: Generated<string | null>;
  updated_at: Generated<Date>;
  updated_by: Generated<number | null>;
}

export interface AssetTypeModelManufacture {
  asset_model_id: Generated<number | null>;
  asset_type_id: Generated<number | null>;
  coldchain_capacity_equipment_id: Generated<number | null>;
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  manufacture_id: Generated<number | null>;
  updated_at: Date;
}

export interface AssetVendors {
  created_at: Date;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  deleted_by: Generated<number | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  type: Generated<string | null>;
  updated_at: Date;
  updated_by: Generated<number | null>;
}

export interface ColdchainCapacityEquipment {
  capacity_nett_at_minus_20_c: Generated<number | null>;
  capacity_nett_at_minus_86_c: Generated<number | null>;
  capacity_nett_at_plus_5_c: Generated<number | null>;
  code_pqs: Generated<string | null>;
  created_at: Generated<Date | null>;
  created_by: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  deleted_by: Generated<number | null>;
  designation_cceigat_id: Generated<number | null>;
  id: Generated<number>;
  status: Generated<number>;
  type_pqs_id: number;
  updated_at: Generated<Date | null>;
  updated_by: Generated<number | null>;
}

export interface DesignationCceigat {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  updated_at: Date;
}

export interface LoggerHistories {
  actual_date: Generated<Date | null>;
  asset_id: Generated<number | null>;
  battery: Generated<number | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  device_code: Generated<string | null>;
  entity_id: Generated<number | null>;
  humidity: Generated<number | null>;
  id: Generated<number>;
  lat: Generated<number | null>;
  logger_status: Generated<string | null>;
  long: Generated<number | null>;
  max_temp: Generated<number | null>;
  min_temp: Generated<number | null>;
  power: Generated<number | null>;
  signal: Generated<number | null>;
  status: Generated<number | null>;
  status_device: Generated<number>;
  temp: Generated<number | null>;
  updated_at: Generated<Date>;
  working_status: Generated<string | null>;
}

export interface Loggers {
  asset_id: Generated<number | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  gsm_no: Generated<string | null>;
  id: Generated<number>;
  location: Generated<string | null>;
  max: Generated<number>;
  min: Generated<number>;
  position: string;
  prod_year: Generated<string | null>;
  serial_number: Generated<string | null>;
  status: Generated<number>;
  temp: Generated<string>;
  updated_at: Generated<Date>;
  vendor: Generated<string | null>;
}

export interface LoggerStatus {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  updated_at: Date;
}

export interface MasterSchedules {
  created_at: Date;
  days: Generated<number | null>;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  title: Generated<string | null>;
  title_en: Generated<string | null>;
  updated_at: Date;
}

export interface SequelizeMeta {
  name: string;
}

export interface SourceAssets {
  created_at: Date;
  created_by: Generated<number>;
  deleted_at: Generated<Date | null>;
  deleted_by: Generated<number | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  name: string;
  updated_at: Date;
  updated_by: Generated<number>;
}

export interface TypePqs {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  updated_at: Date;
}

export interface UnusedReasons {
  created_at: Date;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  name: Generated<string | null>;
  reason_type: Generated<number | null>;
  updated_at: Date;
}

export interface UserAsset {
  asset_id: Generated<number | null>;
  created_at: Generated<Date>;
  deleted_at: Generated<Date | null>;
  id: Generated<number>;
  updated_at: Generated<Date>;
  user_id: Generated<number | null>;
  user_name: Generated<string | null>;
}

export interface ViewAssetsSerialNumber {
  asset_id: Generated<number>;
  count_serial_number: Generated<number>;
  new_serial_number: Generated<string | null>;
  old_serial_number: string;
  serial_number: string;
}

export interface DB {
  asset_communication_providers: AssetCommunicationProviders;
  asset_electricity: AssetElectricity;
  asset_model: AssetModel;
  asset_roles: AssetRoles;
  asset_status: AssetStatus;
  asset_status_excursions: AssetStatusExcursions;
  asset_statuses: AssetStatuses;
  asset_statusess: AssetStatusess;
  asset_type: AssetType;
  asset_type_model_manufacture: AssetTypeModelManufacture;
  asset_vendors: AssetVendors;
  assets: Assets;
  coldchain_capacity_equipment: ColdchainCapacityEquipment;
  designation_cceigat: DesignationCceigat;
  logger_histories: LoggerHistories;
  logger_status: LoggerStatus;
  loggers: Loggers;
  master_schedules: MasterSchedules;
  SequelizeMeta: SequelizeMeta;
  source_assets: SourceAssets;
  type_pqs: TypePqs;
  unused_reasons: UnusedReasons;
  user_asset: UserAsset;
  view_assets_serial_number: ViewAssetsSerialNumber;
}
