/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Decimal = ColumnType<string, number | string>

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface AssetModels {
  asset_type_id: number | null
  capacity: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  manufacture_id: number | null
  name: string | null
  updated_at: Date
  updated_by: number | null
}

export interface Assets {
  asset_type_id: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number | null
  id: Generated<number>
  maintainers_id: number | null
  manufacture_id: number | null
  owners_id: number | null
  production_year: number | null
  serial_number: string | null
  status: number | null
  updated_at: Date
  updated_by: number | null
}

export interface AssetTypes {
  created_at: Date
  id: Generated<number>
  name: string | null
  type: number | null
  updated_at: Date
}

export interface Batches {
  code: string | null
  created_at: Date
  deleted_at: Date | null
  expired_date: Date | null
  id: Generated<number>
  manufacture_id: number | null
  production_date: Date | null
  status: Generated<number | null>
  updated_at: Date
}

export interface BiofarmaOrders {
  alamat: string | null
  biofarma_id: number | null
  biofarma_type: string | null
  code_product_kemenkes: string | null
  created_at: Date
  entrance_type: string | null
  exist_smile: number | null
  expired_date: Date | null
  grant_country: string | null
  id: Generated<number>
  jm_dosis: number | null
  jm_dosis_terima: number | null
  jm_vial: number | null
  jm_vial_terima: number | null
  kode_area: number | null
  manufacture_country: string | null
  no_batch: string | null
  no_do: string | null
  no_document: string | null
  no_po: string | null
  notes: string | null
  pengirim: string | null
  produk: string | null
  released_date: Date | null
  service_type: number | null
  status: string | null
  tanggal_do: Date | null
  tanggal_kirim: Date | null
  tanggal_terima: Date | null
  tujuan: string | null
  updated_at: Date
}

export interface BiofarmaSmdvOrders {
  alamat: string | null
  biofarma_id: number
  created_at: Date
  deleted_at: Date | null
  do_pusat: string | null
  expired_date: Date | null
  id: Generated<number>
  jenis_layanan: string | null
  jumlah_dosis: number | null
  jumlah_vial: number | null
  keterangan: string | null
  kode_area: string | null
  kode_hub: string | null
  nama_produk: string | null
  nama_smdv: string | null
  no_batch: string | null
  nomor_do: string | null
  nomor_po: string | null
  nomor_surat_alokasi: string | null
  pengiriman: string | null
  status: string | null
  tanggal_do: Date | null
  tanggal_pickup: Date | null
  tanggal_terima: Date | null
  tipe_vaksin: string | null
  tujuan_pengiriman: string | null
  updated_at: Date
}

export interface ColdchainCapacityEquipmentUnused {
  capacity_nett_at_minus_20_c: number | null
  capacity_nett_at_minus_86_c: number | null
  capacity_nett_at_plus_5_c: number | null
  code_pqs: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  status: Generated<number | null>
  updated_at: Date
  updated_by: number | null
}

export interface ColdstorageAnnualPlanning {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  id: Generated<number>
  monthly_volume: number | null
  monthly_volume_percent: number | null
  peak_volume_augustus: number | null
  peak_volume_augustus_percent: number | null
  peak_volume_november: number | null
  peak_volume_november_percent: number | null
  peak_volume_q3: number | null
  peak_volume_q3_percent: number | null
  peak_volume_q4: number | null
  peak_volume_q4_percent: number | null
  quartal_volume: number | null
  quartal_volume_percent: number | null
  updated_at: Date
  updated_by: number | null
  year: number
  yearly_child_id: number | null
  yearly_volume: number | null
  yearly_volume_need: number | null
  yearly_volume_need_percent: number | null
  yearly_volume_percent: number | null
}

export interface ColdstorageAnnualPlanningTemperature {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  id: Generated<number>
  monthly_volume: number | null
  peak_volume_augustus: number | null
  peak_volume_november: number | null
  peak_volume_q3: number | null
  peak_volume_q4: number | null
  quartal_volume: number | null
  range_temperature_id: number
  updated_at: Date
  updated_by: number | null
  year: number
  yearly_volume: number | null
  yearly_volume_need: number | null
}

export interface ColdstorageMaterials {
  coldstorage_id: number | null
  created_at: Date
  deleted_at: Date | null
  dosage_stock: number | null
  entity_id: number | null
  id: Generated<number>
  master_material_id: number | null
  max_dosage: number | null
  package_stock: number | null
  package_volume: number | null
  projection_package_stock: number | null
  projection_package_volume: number | null
  projection_stock: number | null
  projection_vial_stock: number | null
  recommend_order_base_on_max: number | null
  remain_package_fulfill: number | null
  updated_at: Date
  vial_stock: number | null
  volume_per_liter: number | null
}

export interface ColdstoragePerTemperature {
  coldstorage_id: number | null
  created_at: Date
  deleted_at: Date | null
  entity_id: number | null
  id: Generated<number>
  percentage_capacity: number | null
  projection_percentage_capacity: number | null
  projection_total_volume: number | null
  projection_volume_asset: number | null
  range_temperature_id: number | null
  total_volume: number | null
  updated_at: Date
  volume_asset: number | null
}

export interface Coldstorages {
  created_at: Date
  deleted_at: Date | null
  entity_id: number | null
  id: Generated<number>
  percentage_capacity: number | null
  projection_percentage_capacity: number | null
  projection_total_volume: number | null
  projection_volume_asset: number | null
  total_volume: number | null
  updated_at: Date
  volume_asset: number | null
}

export interface ColdstorageTransactionLogs {
  created_at: Date
  deleted_at: Date | null
  entity_id: number | null
  id: Generated<number>
  master_material_id: number | null
  status: number | null
  updated_at: Date
}

export interface CommitmentItems {
  commitment_id: number
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  dose_quantity: number
  id: Generated<number>
  material_id: number
  province_id: string
  service_type_id: number
  updated_at: Date
  updated_by: number | null
  vial_quantity: number
}

export interface Commitments {
  contract_date: Date
  contract_end_date: Date | null
  contract_number: string
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  information: string | null
  updated_at: Date
  updated_by: number | null
  vendor_id: number
  year: string
}

export interface Configurations {
  created_at: Date | null
  deleted_at: Date | null
  id: Generated<number>
  key: string
  updated_at: Date | null
  value: string | null
}

export interface Contracts {
  contract_number: string
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface CustomerVendors {
  created_at: Date | null
  customer_id: number | null
  deleted_at: Date | null
  is_consumption: Generated<number>
  is_distribution: Generated<number>
  is_extermination: Generated<number>
  updated_at: Date | null
  vendor_id: number | null
}

export interface CustomerVendors290824 {
  created_at: Date | null
  customer_id: number | null
  deleted_at: Date | null
  is_consumption: Generated<number>
  is_distribution: Generated<number>
  is_extermination: Generated<number>
  updated_at: Date | null
  vendor_id: number | null
}

export interface DashboardSatusehat {
  api_url: string | null
  created_at: Date
  created_by: number | null
  dashboard_name: string | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  sort: number | null
  updated_at: Date
  updated_by: number | null
  uuid: string | null
}

export interface DinOrderItems {
  created_at: Date
  din_order_id: number | null
  entrance_type: string | null
  expired_date: Date | null
  grant_country: string | null
  id: Generated<number>
  jm_dosis: number | null
  jm_dosis_terima: number | null
  jm_vial: number | null
  jm_vial_terima: number | null
  keterangan: string | null
  kfa_code: string | null
  lot_no: string | null
  manufacture_country: string | null
  no_batch: string | null
  note: string | null
  product_code: string | null
  production_date: Date | null
  produk: string | null
  released_date: Date | null
  tanggal_release: Date | null
  total_price: number | null
  unit: string | null
  unit_price: number | null
  updated_at: Date
}

export interface DinOrders {
  activity_code: string | null
  alamat: string | null
  alamat_penerima: string | null
  alamat_pengirim: string | null
  biaya_transport: number | null
  biofarma_id: number | null
  carrier: string | null
  carrier_ref: string | null
  created_at: Date
  din_type: string | null
  exist_smile: number | null
  id: Generated<number>
  jenis_layanan: string | null
  kabkota_id_penerima: number | null
  kabkota_id_pengirim: number | null
  kabkota_penerima: string | null
  kabkota_pengirim: string | null
  kecamatan_id_penerima: number | null
  kecamatan_id_pengirim: number | null
  kecamatan_penerima: string | null
  kecamatan_pengirim: string | null
  kelurahan_id_penerima: number | null
  kelurahan_id_pengirim: number | null
  kelurahan_penerima: string | null
  kelurahan_pengirim: string | null
  key_ssl: string | null
  kode_area: number | null
  kode_penerima: string | null
  kode_pengirim: string | null
  kodepos_penerima: string | null
  kodepos_pengirim: string | null
  line: string | null
  line_ref: string | null
  nama_pengirim: string | null
  no_do: string | null
  no_document: string | null
  no_po: string | null
  notes: string | null
  pengirim: string | null
  program: string | null
  provinsi_id_penerima: number | null
  provinsi_id_pengirim: number | null
  provinsi_penerima: string | null
  provinsi_pengirim: string | null
  service_type: string | null
  status: string | null
  sumber_dana: string | null
  tanggal_do: Date | null
  tanggal_kirim: Date | null
  tanggal_terima: Date | null
  total_transaksi: number | null
  tujuan: string | null
  type_penerima: string | null
  updated_at: Date
}

export interface DownloadLogs {
  created_at: Date
  deleted_at: Date | null
  download_url: string | null
  id: Generated<number>
  status: number
  updated_at: Date
  user_id: number
}

export interface Educations {
  created_at: Date | null
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string
  title_en: string
  updated_at: Date | null
  updated_by: number | null
}

export interface Entities {
  accuracy: string | null
  address: string | null
  bpom_key: string | null
  code: string | null
  code_new: string | null
  code_old: string | null
  code_satu_sehat: string | null
  country: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  gps_errors: string | null
  id: Generated<number>
  is_ayosehat: Generated<number>
  is_puskesmas: Generated<number | null>
  is_vendor: Generated<number>
  last_transaction_at: Date | null
  lat: string | null
  lng: string | null
  name: string | null
  postal_code: string | null
  province_id: string | null
  province_id_new: string | null
  province_id_old: string | null
  regency_id: string | null
  regency_id_new: string | null
  regency_id_old: string | null
  region_id: number | null
  rutin_join_date: Date | null
  status: Generated<number | null>
  sub_district_id: string | null
  sub_district_id_new: string | null
  sub_district_id_old: string | null
  type: Generated<number | null>
  updated_at: Date
  updated_by: number | null
  village_id: string | null
  village_id_new: string | null
  village_id_old: string | null
}

export interface EntityActivityDate {
  activity_id: number
  created_at: Date
  deleted_at: Date | null
  end_date: Date | null
  entity_id: number
  id: Generated<number>
  join_date: Date | null
  updated_at: Date
}

export interface EntityEntityTags {
  created_at: Generated<Date | null>
  entity_id: number
  entity_tag_id: number
  id: Generated<number>
  updated_at: Generated<Date | null>
}

export interface EntityHasMasterMaterials {
  allocated_stock: Generated<number>
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number | null
  extermination_discard_qty: Generated<number>
  extermination_qty: Generated<number>
  extermination_received_qty: Generated<number>
  extermination_shipped_qty: Generated<number>
  id: Generated<number>
  master_material_id: number | null
  max: Generated<number>
  min: Generated<number>
  on_hand_stock: Generated<number>
  stock_last_update: Date | null
  total_open_vial: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface EntityMasterMaterialActivities {
  activity_id: number | null
  allocated: Generated<number | null>
  consumption_rate: Generated<number>
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  entity_master_material_id: number | null
  id: Generated<number>
  max: Generated<number | null>
  min: Generated<number | null>
  retailer_price: Generated<number>
  stock_on_hand: Generated<number | null>
  tax: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface EntityMasterMaterialActivities03102022 {
  activity_id: number | null
  consumption_rate: Generated<number>
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  entity_master_material_id: number | null
  id: Generated<number>
  max: Generated<number | null>
  min: Generated<number | null>
  retailer_price: Generated<number>
  tax: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface EntityMasterMaterialMinmax {
  created_at: Generated<Date | null>
  created_by: number
  deleted_at: Date | null
  emma_id: number
  id: Generated<number>
  max: number
  min: number
  updated_at: Generated<Date | null>
  updated_by: number
  year: number | null
  yearly_plan_id: number
}

export interface EntityPrepMinMax {
  created_at: Date | null
  distribution_time: number | null
  entity_id: number | null
  lead_time: number | null
  updated_at: Date | null
}

export interface EntityTags {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  title_en: string | null
  updated_at: Date
}

export interface EntityTagsOld {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  updated_at: Date
}

export interface Ethnics {
  created_at: Date | null
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string
  title_en: string
  updated_at: Date | null
  updated_by: number | null
}

export interface EventReportChildReasons {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  parent_id: number | null
  title: string | null
  title_en: string | null
  updated_at: Date
}

export interface EventReportComments {
  comment: string | null
  created_at: Date
  deleted_at: Date | null
  event_report_id: number | null
  id: Generated<number>
  status: number | null
  updated_at: Date
  user_id: number | null
}

export interface EventReportHistories {
  created_at: Date
  event_report_id: number
  id: Generated<number>
  status: number
  updated_at: Date
  updated_by: number
}

export interface EventReportItems {
  child_reason_id: number | null
  created_at: Date
  custom_material: string | null
  deleted_at: Date | null
  event_report_id: number
  expired_date: Date | null
  id: Generated<number>
  material_id: number | null
  no_batch: string | null
  production_date: Date | null
  qty: Generated<number>
  reason_id: number | null
  updated_at: Date
}

export interface EventReportReasons {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  title_en: string | null
  updated_at: Date
}

export interface EventReports {
  arrived_date: Date
  canceled_at: Date | null
  canceled_by: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  finished_at: Date | null
  finished_by: number | null
  has_order: Generated<number>
  id: Generated<number>
  link: string | null
  no_packing_slip: string | null
  order_id: number | null
  status: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface ExterminationFlowReasons {
  createdAt: Date
  deletedAt: Date | null
  flow_id: number | null
  id: Generated<number>
  transaction_reason_id: number | null
  updatedAt: Date
}

export interface ExterminationFlows {
  createdAt: Date
  deletedAt: Date | null
  id: Generated<number>
  title: string | null
  updatedAt: Date
}

export interface ExterminationTransactions {
  activity_id: number
  change_qty: Generated<number>
  close_vial: Generated<number>
  created_by: number | null
  createdAt: Date
  customer_id: number | null
  deleted_at: Date | null
  entity_id: number
  extermination_transaction_type_id: number
  flow_id: Generated<number | null>
  id: Generated<number>
  master_material_id: number
  material_id: number | null
  open_vial: Generated<number>
  opening_qty: Generated<number>
  order_id: number | null
  stock_extermination_id: number
  updated_by: number | null
  updatedAt: Date
  vendor_id: number | null
}

export interface ExterminationTransactionTypes {
  createdAt: Date
  deletedAt: Date | null
  id: Generated<number>
  title: string | null
  title_en: string | null
  updatedAt: Date | null
}

export interface IntegrationAsikAggregate {
  aggregate: number | null
  batch_code_smile: string | null
  batch_id_smile: number | null
  batch_number_asik: string | null
  createdAt: Date
  customer_id: number | null
  deletedAt: Date | null
  id: Generated<number>
  injection_date: Date | null
  input_date: Date | null
  master_material_id: number | null
  page: number | null
  pos_imunisasi_asik: string | null
  pos_imunisasi_asik_province_id: number | null
  pos_imunisasi_asik_regency_id: number | null
  pos_imunisasi_asik_subdistrict_id: number | null
  puskesmas_asik: string | null
  puskesmas_asik_province_id: number | null
  puskesmas_asik_regency_id: number | null
  puskesmas_asik_subdistrict_id: number | null
  updatedAt: Date | null
  vaksin_asik: string | null
  vendor_id: number | null
}

export interface IntegrationAyoSehat {
  activity_id: number | null
  batch_id: number | null
  consumed_qty: number | null
  consumed_qty_closevial: number | null
  consumed_qty_openvial: number | null
  consumed_status: number | null
  created_at: Date
  created_at_consumed_smile: Date | null
  created_at_injection: Date | null
  created_at_return_vaccination: Date | null
  created_by: number | null
  customer_id: number | null
  deleted_at: Date | null
  id: Generated<number>
  injection_qty: number | null
  integration_status: Generated<number>
  material_id: number | null
  return_qty: number | null
  return_qty_closevial: number | null
  return_qty_openvial: number | null
  return_status: number | null
  return_validation: number | null
  session_id: string | null
  status_vvm: number | null
  stock_id: number | null
  transaction_id_consumed: number | null
  transaction_id_injection: number | null
  transaction_id_return: number | null
  updated_at: Date
  updated_at_return_vaccination: Date | null
  vendor_id: number | null
}

export interface IntegrationOrderItems {
  confirmed_qty: number | null
  created_at: Date
  created_by: number
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  integration_order_id: number
  master_material_id: number
  other_reason: string | null
  qty: number
  reason_id: number | null
  recomended_stock: number | null
  updated_at: Date
  updated_by: number
}

export interface IntegrationOrderItemsKfa {
  code_kfa_product_template: string
  confirmed_qty: number | null
  created_at: Date
  created_by: number
  deleted_at: Date | null
  deleted_by: number | null
  external_order_item_id: string | null
  id: Generated<number>
  integration_order_id: number
  other_reason: string | null
  product_code: string
  qty: number
  reason_id: number | null
  recomended_stock: number | null
  updated_at: Date
  updated_by: number
}

export interface IntegrationOrderLogs {
  action_type: string | null
  created_at: Date
  deleted_at: Date | null
  endpoint: string | null
  error_message: string | null
  http_method: string | null
  http_status_code: number | null
  id: Generated<number>
  integration_order_id: number
  order_id: number
  request_body: string | null
  request_headers: string | null
  response_body: string | null
  response_headers: string | null
  status: string | null
  system_source: string
  system_target: string | null
  timestamp: Generated<Date | null>
  updated_at: Date
}

export interface IntegrationOrders {
  activity_id: number
  category: string | null
  created_at: Date
  created_by: number
  customer_id: number
  deleted_at: Date | null
  deleted_by: number | null
  existing_smile_order_id: number
  id: Generated<number>
  is_validate: number | null
  key_ssl: string | null
  no_surat: string | null
  status: number
  system_source: string | null
  total_patients: number | null
  type: number
  updated_at: Date
  updated_by: number
  vendor_id: number
}

export interface KfaLevels {
  code: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  order_number: number | null
  updated_at: Date
  updated_by: number | null
}

export interface LoginAttempts {
  hit: number
  id: Generated<number>
  ip: string | null
  last_attempt: Generated<Date | null>
}

export interface Manufactures {
  address: string | null
  contact_name: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  description: string | null
  email: string | null
  id: Generated<number>
  is_asset: Generated<number>
  name: string | null
  phone_number: string | null
  production_date: Date | null
  production_year: number | null
  reference_id: string | null
  status: Generated<number | null>
  type: Generated<number>
  updated_at: Date
  updated_by: number | null
  village_id: string | null
}

export interface MappingCancelDiscard {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  transaction_cancel_discard_id: number
  transaction_discard_id: number
  updated_at: Date
}

export interface MappingEntities {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  id_bpjs: number | null
  id_entitas_smile: number | null
  id_pusdatin: number | null
  id_satu_sehat: number | null
  updated_at: Date
}

export interface MappingMasterMaterials {
  asik_name: string | null
  code_biofarma: string | null
  code_bpom: string | null
  code_kfa_ingredients: string | null
  code_kfa_packaging: string | null
  code_kfa_product_template: string | null
  code_kfa_product_variant: string | null
  code_siha: string | null
  code_sitb: string | null
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  id_kfa: string | null
  id_material_smile: number | null
  name_kfa_ingredients: string | null
  name_kfa_packaging: string | null
  name_kfa_product_template: string | null
  name_kfa_product_variant: string | null
  name_material_smile: string | null
  name_siha: string | null
  name_sitb: string | null
  updated_at: Date
}

export interface MappingMasterMaterials030924 {
  asik_name: string | null
  code_biofarma: string | null
  code_bpom: string | null
  code_kfa_ingredients: string | null
  code_kfa_packaging: string | null
  code_kfa_product_template: string | null
  code_kfa_product_variant: string | null
  created_at: Date
  deleted_at: Date | null
  id: number
  id_kfa: string | null
  id_material_smile: number | null
  name_kfa_ingredients: string | null
  name_kfa_packaging: string | null
  name_kfa_product_template: string | null
  name_kfa_product_variant: string | null
  name_material_smile: string | null
  updated_at: Date
}

export interface MasterActivities {
  code: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  is_ordered_purchase: Generated<number>
  is_ordered_sales: Generated<number>
  is_patient_id: Generated<number | null>
  name: string | null
  updated_at: Date
  updated_by: number | null
}

export interface MasterIpvs {
  activity_id: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  has_ipv: Generated<number | null>
  id: Generated<number>
  ipv: Generated<Decimal>
  master_material_id: number | null
  material_id: number | null
  updated_at: Date
  updated_by: number | null
}

export interface MasterKodeWilayah {
  code: string | null
  kode_bps: string | null
  kode_lama: string | null
  level: number | null
  name: string | null
  parent: string | null
  state: string | null
}

export interface MasterMaterialHasActivities {
  activity_id: number | null
  created_at: Generated<Date | null>
  id: Generated<number>
  master_material_id: number | null
  updated_at: Generated<Date | null>
}

export interface MasterMaterialHasCompanions {
  id: Generated<number>
  master_material_companion_id: number | null
  master_material_id: number | null
}

export interface MasterMaterialHasConditions {
  created_at: Date
  id: Generated<number>
  key: string | null
  master_material_id: number | null
  type: number | null
  updated_at: Date
  value: string | null
}

export interface MasterMaterialHasManufactures {
  id: Generated<number>
  manufacture_id: number | null
  master_material_id: number | null
}

export interface MasterMaterials {
  bpom_code: string | null
  code: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  description: string | null
  id: Generated<number>
  is_addremove: Generated<number>
  is_openvial: Generated<number>
  is_so: Generated<number | null>
  is_stockcount: Generated<number>
  is_vaccine: number | null
  kfa_code: string | null
  kfa_level_id: number | null
  managed_in_batch: Generated<number>
  name: string | null
  need_sequence: number | null
  parent_id: number | null
  pieces_per_unit: Generated<number>
  range_temperature_id: number | null
  status: Generated<number>
  temperature_max: number | null
  temperature_min: number | null
  temperature_sensitive: number | null
  unit: string | null
  unit_of_distribution: string | null
  updated_at: Date
  updated_by: number | null
}

export interface MasterMaterialsCopy {
  bpom_code: string | null
  code: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  description: string | null
  id: number
  is_addremove: Generated<number>
  is_openvial: Generated<number>
  is_stockcount: Generated<number>
  is_vaccine: Generated<number>
  managed_in_batch: Generated<number>
  name: string | null
  pieces_per_unit: Generated<number>
  status: Generated<number>
  temperature_max: number | null
  temperature_min: number | null
  temperature_sensitive: number | null
  unit: string | null
  updated_at: Date
  updated_by: number | null
}

export interface MasterMaterialType {
  activity_id: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  id: Generated<number>
  name: string | null
  updated_at: Date | null
  updated_by: number | null
}

export interface MasterTarget {
  created_at: Date
  id: Generated<number>
  name: string | null
  updated_at: Date
}

export interface MasterTargetDistributions {
  activity_id: number | null
  created_at: Date
  created_by: number | null
  custom_percentage: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  master_material_id: number | null
  master_target_id: number
  material_id: number
  qty: Generated<number>
  updated_at: Date
  updated_by: number | null
}

export interface MasterTargetRegencies {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  id: Generated<number>
  master_target_id: number
  qty: Generated<number>
  updated_at: Date
  updated_by: number | null
  year: string | null
}

export interface MasterVolumeMaterialManufactures {
  box_height: number | null
  box_length: number | null
  box_width: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  id: Generated<number>
  manufacture_id: number | null
  master_material_id: number | null
  pieces_per_unit: number | null
  unit_per_box: number | null
  updated_at: Date
  updated_by: number | null
}

export interface MaterialCategories {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  name: string
  updated_at: Date
}

export interface MaterialCompanions {
  id: Generated<number>
  material_companion_id: number
  material_id: number
}

export interface MaterialConditions {
  created_at: Date
  id: Generated<number>
  key: string
  material_id: number | null
  type: Generated<number>
  updated_at: Date
  value: string | null
}

export interface MaterialEntity {
  abnormality_duration_days: number | null
  abnormality_type: string | null
  allocated_qty: Generated<number>
  consumption_rate: number | null
  consumption_rate_month: number | null
  consumption_rate_week: number | null
  created_at: Date
  created_by: number | null
  days_stock: number | null
  deleted_at: Date | null
  deleted_by: number | null
  demand_forecast: number | null
  entity_id: number | null
  id: Generated<number>
  inventory_policy: string | null
  lead_time_days: number | null
  lead_time_demand: number | null
  material_id: number | null
  max: number | null
  max_updated_at: Date | null
  min: number | null
  min_updated_at: Date | null
  on_hand_qty: Generated<number>
  optimal_order_quantity: number | null
  order_periodicity_days: number | null
  retailer_price: number | null
  retailer_price_updated_at: Date | null
  safety_stock: number | null
  service_level: number | null
  tax: number | null
  updated_at: Date
  updated_by: number | null
}

export interface MaterialManufacture {
  created_at: Date
  id: Generated<number>
  manufacture_id: number | null
  material_id: number | null
  updated_at: Date
}

export interface MaterialMaterialCategories {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  master_material_id: number
  material_category_id: number
  updated_at: Date
}

export interface MaterialMaterialTag {
  created_at: Date | null
  id: Generated<number>
  material_id: number | null
  material_tag_id: number | null
  updated_at: Date | null
}

export interface Materials {
  bpom_code: number | null
  code: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  description: string | null
  id: Generated<number>
  is_addremove: Generated<number>
  is_stockcount: Generated<number | null>
  is_vaccine: Generated<number>
  managed_in_batch: Generated<number>
  master_activity_id: number | null
  master_material_id: number | null
  name: string | null
  pieces_per_unit: Generated<number>
  status: Generated<number | null>
  temperature_max: number | null
  temperature_min: number | null
  temperature_sensitive: number | null
  unit: string | null
  updated_at: Date
  updated_by: number | null
}

export interface MaterialTags {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  is_ordered_purchase: Generated<number | null>
  is_ordered_sales: Generated<number | null>
  title: string | null
  updated_at: Date
}

export interface NewOpnameItems {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  master_material_id: number | null
  material_id: number | null
  new_opname_id: number
  updated_at: Date
}

export interface NewOpnames {
  activity_id: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  id: Generated<number>
  period_id: number | null
  status: number | null
  updated_at: Date
  updated_by: number | null
}

export interface NewOpnameStocks {
  batch_code: string | null
  batch_id: number | null
  created_at: Date
  deleted_at: Date | null
  expired_date: Date | null
  id: Generated<number>
  new_opname_item_id: number
  real_qty: Generated<number>
  smile_qty: Generated<number>
  stock_id: number | null
  unsubmit_distribution_qty: Generated<number>
  unsubmit_return_qty: Generated<number>
  updated_at: Date
}

export interface NotificationTypes {
  created_at: Generated<Date | null>
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  title_en: string | null
  type: string | null
  updated_at: Generated<Date | null>
}

export interface Occupations {
  created_at: Date | null
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string
  title_en: string
  updated_at: Date | null
  updated_by: number | null
}

export interface OpnameActions {
  created_at: Date
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string | null
  updated_at: Date
  updated_by: number | null
}

export interface OpnameItemReasonActions {
  created_at: Date
  id: Generated<number>
  opname_action_id: number | null
  opname_reason_id: number | null
  opname_stock_item_id: number | null
  updated_at: Date
}

export interface OpnamePeriod {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  end_date: Date | null
  id: Generated<number>
  month_periode: number | null
  start_date: Date | null
  status: Generated<number | null>
  updated_at: Date
  updated_by: number | null
  year_periode: number | null
}

export interface OpnameReasons {
  created_at: Date
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string | null
  updated_at: Date
  updated_by: number | null
}

export interface OpnameStockItems {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  opname_stock_id: number | null
  real_qty: Generated<number>
  smile_qty: Generated<number>
  stock_category: number
  updated_at: Date
  updated_by: number | null
}

export interface OpnameStocks {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  end_date: Date
  entity_id: number
  id: Generated<number>
  material_id: number
  start_date: Date
  updated_at: Date
  updated_by: number | null
}

export interface OrderComments {
  comment: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  order_id: number
  order_status: number | null
  updated_at: Date
  updated_by: number | null
  user_id: number
}

export interface OrderHistories {
  created_at: Date
  id: Generated<number>
  order_id: number | null
  status: number | null
  updated_at: Date
  updated_by: number | null
}

export interface OrderItemProjectionCapacities {
  capacity_asset: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  is_confirm: Generated<number>
  order_id: number
  percent_capacity: number | null
  total_volume: number | null
  updated_at: Date
  updated_by: number | null
}

export interface OrderItems {
  confirmed_qty: Generated<number>
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  master_material_id: number | null
  material_id: number | null
  order_id: number
  order_item_kfa_id: number | null
  other_reason: string | null
  qty: number | null
  reason_id: number | null
  recommended_stock: number | null
  updated_at: Date
  updated_by: number | null
}

export interface OrderItemsKfa {
  code_kfa_product_template: string | null
  confirmed_qty: number | null
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  order_id: number
  other_reason: string | null
  qty: number | null
  reason_id: number | null
  recomended_stock: number | null
  updated_at: Date
  validated_qty: number | null
}

export interface OrderOrderTag {
  created_at: Date
  id: Generated<number>
  order_id: number | null
  order_tag_id: number | null
  updated_at: Date
}

export interface OrderReports {
  arrived_date: Date | null
  arrived_qty: number
  batch_code: string | null
  batch_expired: Date | null
  batch_production: Date | null
  created_at: Date
  deleted_at: Date | null
  entity_id: number | null
  id: Generated<number>
  material_id: number | null
  message: string | null
  updated_at: Date
}

export interface Orders {
  activity_id: number | null
  actual_shipment: Date | null
  allocated_at: Date | null
  allocated_by: number | null
  biofarma_changed: number | null
  cancel_reason: number | null
  cancelled_at: Date | null
  cancelled_by: number | null
  confirmed_at: Date | null
  confirmed_by: number | null
  created_at: Date
  created_by: number | null
  customer_id: number
  deleted_at: Date | null
  deleted_by: number | null
  delivery_number: string | null
  device_type: number | null
  easygo_no_do: string | null
  estimated_date: Date | null
  fulfilled_at: Date | null
  fulfilled_by: number | null
  id: Generated<number>
  is_allocated: Generated<number | null>
  is_kpcpen: number | null
  is_manual: number | null
  master_order_id: number | null
  no_document: string | null
  no_po: string | null
  notes: string | null
  other_reason: string | null
  purchase_ref: string | null
  qty_kpcpen: number | null
  reason: number | null
  released_date: Date | null
  required_date: Date | null
  sales_ref: string | null
  service_type: number | null
  shipped_at: Date | null
  shipped_by: number | null
  status: number
  submit_kpcpen_at: Date | null
  taken_by_customer: Generated<number | null>
  track_device_id: number | null
  type: number
  updated_at: Date
  updated_by: number | null
  validated_at: Date | null
  validated_by: number | null
  vendor_id: number
}

export interface OrderStockExterminations {
  allocated_discard_qty: Generated<number>
  allocated_received_qty: Generated<number>
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  order_stock_id: number | null
  received_qty: Generated<number>
  status: number
  stock_extermination_id: number | null
  updated_at: Date | null
  updated_by: number | null
}

export interface OrderStockPurchase {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  order_stock_id: number | null
  pieces_purchase_id: number | null
  price: number | null
  source_material_id: number | null
  total_price: number | null
  updated_at: Date
  year: number | null
}

export interface OrderStocks {
  allocated_qty: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  fulfill_reason: number | null
  fulfill_status: number | null
  id: Generated<number>
  order_item_id: number | null
  ordered_qty: number | null
  other_reason: string | null
  qrcode: string | null
  received_qty: number | null
  status: number | null
  stock_id: number | null
  updated_at: Date
  updated_by: number | null
}

export interface OrderTags {
  created_at: Date
  id: Generated<number>
  title: string | null
  updated_at: Date
}

export interface Patients {
  address: string | null
  birth_date: Date | null
  created_at: Generated<Date | null>
  deleted_at: Date | null
  dengue_month_before: string | null
  dengue_received_medicine: number | null
  dengue_received_vaccine: number | null
  dengue_year_before: string | null
  education_id: number | null
  entity_id: number | null
  ethnic_id: number | null
  gender: number | null
  id: Generated<number>
  identity_type: Generated<number>
  is_dengue_before: number | null
  last_dengue_diagnosis: Date | null
  last_preexposure_at: Date | null
  last_vaccine_at: Date | null
  marital_status: number | null
  name: string | null
  nik: string | null
  occupation_id: number | null
  phone_number: string | null
  pos_code: string | null
  preexposure_sequence: number | null
  religion_id: number | null
  rt: string | null
  rw: string | null
  stop_notification: Generated<number | null>
  updated_at: Generated<Date | null>
  vaccine_method: Generated<number | null>
  vaccine_sequence: number | null
  village_id: number | null
}

export interface PiecesPurchase {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  name: string | null
  updated_at: Date | null
}

export interface Provinces {
  created_at: Date
  deleted_at: Date | null
  id: string
  lat: string | null
  lng: string | null
  name: string | null
  province_id_new: string | null
  province_id_old: string | null
  updated_at: Date
  zoom: string | null
}

export interface RabiesVaccineRules {
  active_duration: number | null
  created_at: Date | null
  deleted_at: Date | null
  end_notification: number | null
  id: Generated<number>
  next_duration: number | null
  sequence: number
  start_notification: number | null
  updated_at: Date
}

export interface RangeTemperature {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  temperature_max: number
  temperature_min: number
  updated_at: Date
  updated_by: number | null
}

export interface Reactions {
  created_at: Date | null
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string
  title_en: string
  updated_at: Date | null
  updated_by: number | null
}

export interface Reconciliation {
  activity_id: number
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  end_date: Date
  entity_id: number
  id: Generated<number>
  master_material_id: number
  start_date: Date
  updated_at: Date
  updated_by: number | null
}

export interface ReconciliationItemReasonActions {
  action_id: number | null
  created_at: Date
  id: Generated<number>
  reason_id: number | null
  reconciliation_item_id: number | null
  updated_at: Date
}

export interface ReconciliationItems {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  real_qty: Generated<number | null>
  reconciliation_id: number
  smile_qty: Generated<number | null>
  stock_category: number
  updated_at: Date
  updated_by: number | null
}

export interface Regencies {
  created_at: Date
  deleted_at: Date | null
  id: string
  lat: string | null
  lng: string | null
  name: string | null
  province_id: string | null
  province_id_new: string | null
  province_id_old: string | null
  regency_id_new: string | null
  regency_id_old: string | null
  updated_at: Date
}

export interface RegenciesBackup20240108 {
  created_at: Date
  deleted_at: Date | null
  id: string
  lat: string | null
  lng: string | null
  name: string | null
  province_id: string | null
  updated_at: Date
}

export interface Regions {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  name: string | null
  parent_id: number | null
  type: number | null
  updated_at: Date
  updated_by: number | null
}

export interface Religions {
  created_at: Date | null
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  title: string
  title_en: string
  updated_at: Date | null
  updated_by: number | null
}

export interface RequestOrderItems {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  material_id: number | null
  qty: Generated<number>
  request_order_id: number | null
  updated_at: Date
}

export interface RequestOrders {
  buffer_tag: number | null
  created_at: Date
  created_by: number | null
  customer_id: number
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  sales_ref: string | null
  updated_at: Date
  updated_by: number | null
  vendor_id: number
}

export interface ResetPasswords {
  createdAt: Date
  email: string | null
  expired_at: Date | null
  id: Generated<number>
  token: string | null
  updatedAt: Date
}

export interface SequelizeMeta {
  name: string
}

export interface ServiceTypes {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  name: string
  updated_at: Date
}

export interface SourceMaterials {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  name: string | null
  updated_at: Date | null
}

export interface StockActivityMigrationLogs {
  added_transaction_id: number | null
  batch_code: string | null
  batch_id: number | null
  created_at: Generated<Date>
  entity_id: number
  error_message: string | null
  id: Generated<number>
  material_id: number
  new_activity_id: number
  new_stock_id: number | null
  new_stock_qty: Decimal | null
  old_activity_id: number
  old_stock_id: number | null
  old_stock_qty: Decimal | null
  qty_moved: Decimal
  removed_transaction_id: number | null
  stock_status: string | null
  updated_at: Generated<Date>
  user_id: number | null
}

export interface StockExterminations {
  created_by: number | null
  createdAt: Date
  extermination_discard_qty: Generated<number>
  extermination_qty: Generated<number>
  extermination_received_qty: Generated<number>
  extermination_shipped_qty: Generated<number>
  id: Generated<number>
  stock_id: number | null
  transaction_reason_id: number | null
  updated_by: number | null
  updatedAt: Date
}

export interface StockIntervals {
  change_qty: number | null
  closing_qty: number | null
  created_at: Date
  current_stock: number | null
  customer_id: number | null
  date: Date | null
  deleted_at: Date | null
  entity_id: number | null
  entity_name: string | null
  entity_province_id: number | null
  entity_province_name: string | null
  entity_regency_id: number | null
  entity_regency_name: string | null
  entity_sub_district_id: number | null
  entity_sub_district_name: string | null
  entity_tags: string | null
  entity_village_id: number | null
  entity_village_name: string | null
  id: Generated<number>
  material_entity_id: number | null
  material_id: number | null
  material_name: string | null
  material_tags: string | null
  max: number | null
  min: number | null
  opening_qty: number | null
  order_id: number | null
  status_condition: string | null
  stock_id: number | null
  transaction_id: number | null
  transaction_type_id: number | null
  updated_at: Date
  vendor_id: number | null
}

export interface Stocks {
  activity_id: number | null
  allocated: Generated<number | null>
  batch_id: number | null
  budget_source: number | null
  created_by: number | null
  createdAt: Date
  entity_has_material_id: number | null
  extermination_discard_qty: Generated<number>
  extermination_qty: Generated<number>
  extermination_received_qty: Generated<number>
  extermination_shipped_qty: Generated<number>
  id: Generated<number>
  in_transit: number | null
  material_entity_id: number | null
  open_vial: Generated<number>
  price: number | null
  qty: number
  status: number | null
  total_price: number | null
  updated_by: number | null
  updatedAt: Date
  year: number | null
}

export interface StopNotificationHistories {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  patient_id: number
  reason_id: number
  stop_status: Generated<number | null>
  updated_at: Date
  updated_by: number | null
}

export interface StopNotificationReasons {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  type: Generated<string | null>
  updated_at: Date
}

export interface SubDistricts {
  created_at: Date
  deleted_at: Date | null
  id: string
  name: string | null
  regency_id: string | null
  regency_id_new: string | null
  regency_id_old: string | null
  sub_district_id_new: string | null
  sub_district_id_old: string | null
  updated_at: Date
}

export interface SubDistrictsBackup20240108 {
  created_at: Date
  deleted_at: Date | null
  id: string
  name: string | null
  regency_id: string | null
  updated_at: Date
}

export interface Timezones {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  updated_at: Date
  utc_relative: number | null
}

export interface TrackDevices {
  created_at: Date
  device_number: string | null
  entity_id: number | null
  id: Generated<number>
  mobile_phone: string | null
  nopol: string | null
  updated_at: Date
}

export interface TrackingLogEg {
  created_at: Date
  curr_temp: number | null
  deleted_at: Date | null
  id: Generated<number>
  is_alarm: number | null
  lat: number | null
  lon: number | null
  no_do: string | null
  nopol: string | null
  status_do: string | null
  updated_at: Date
  updated_time: Date
  vehicle_status: number | null
}

export interface TransactionInjections {
  created_at: Date
  deleted_at: Date | null
  dose_1: number | null
  dose_2: number | null
  dose_booster: number | null
  dose_routine: number | null
  id: Generated<number>
  transaction_id: number
  updated_at: Date
}

export interface TransactionItems {
  created_at: Date
  created_by: number | null
  id: Generated<number>
  stock_id: number
  transaction_id: number
  updated_at: Date
  updated_by: number | null
}

export interface TransactionPatientReactions {
  actual_date: Date | null
  created_at: Date | null
  deleted_at: Date | null
  id: Generated<number>
  other_reaction: string | null
  patient_id: number
  reaction_id: number
  transaction_patient_id: number
  updated_at: Date | null
}

export interface TransactionPatients {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  other_reaction: string | null
  patient_id: number
  phone_number: string | null
  reaction_id: number | null
  transaction_date: Date | null
  transaction_id: number
  transaction_type_id: number | null
  updated_at: Date
  vaccine_method: number | null
  vaccine_sequence: number | null
}

export interface TransactionPurchase {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  pieces_purchase_id: number | null
  price: number | null
  source_material_id: number | null
  total_price: number | null
  transaction_id: number | null
  updated_at: Date | null
  year: number | null
}

export interface TransactionReasons {
  createdAt: Date
  deletedAt: Date | null
  id: Generated<number>
  is_other: Generated<number>
  is_purchase: Generated<number | null>
  title: string | null
  title_en: string | null
  transaction_type_id: number | null
  updatedAt: Date
}

export interface Transactions {
  activity_id: number | null
  actual_transaction_date: Date | null
  booster: number | null
  change_qty: number
  close_vial: number | null
  commit_datetime: Date | null
  created_by: number | null
  createdAt: Date
  customer_id: number | null
  deleted_at: Date | null
  device_type: Generated<number>
  dose_1: number | null
  dose_2: number | null
  entity_id: number
  id: Generated<number>
  master_material_id: number | null
  material_id: number | null
  open_vial: number | null
  opening_qty: number
  order_id: number | null
  other_reason: string | null
  patient_id: number | null
  preexposure_method: number | null
  stock_id: number
  transaction_reason_id: number | null
  transaction_type_id: number
  updated_by: number | null
  updatedAt: Date
  vaccine_sequence: number | null
  vendor_id: number | null
}

export interface TransactionsCopy220623 {
  activity_id: number | null
  booster: number | null
  change_qty: number
  close_vial: number | null
  created_by: number | null
  createdAt: Date
  customer_id: number | null
  deleted_at: Date | null
  device_type: Generated<number>
  dose_1: number | null
  dose_2: number | null
  entity_id: number
  id: number
  master_material_id: number | null
  material_id: number | null
  open_vial: number | null
  opening_qty: number
  order_id: number | null
  other_reason: string | null
  stock_id: number
  transaction_reason_id: number | null
  transaction_type_id: number
  updated_by: number | null
  updatedAt: Date
  vendor_id: number | null
}

export interface TransactionsLast3months {
  activity_id: number | null
  actual_transaction_date: Date | null
  booster: number | null
  change_qty: number
  close_vial: number | null
  commit_datetime: Date | null
  created_by: number | null
  createdAt: Date
  customer_id: number | null
  deleted_at: Date | null
  device_type: Generated<number>
  dose_1: number | null
  dose_2: number | null
  entity_id: number
  id: Generated<number>
  master_material_id: number | null
  material_id: number | null
  open_vial: number | null
  opening_qty: number
  order_id: number | null
  other_reason: string | null
  patient_id: number | null
  stock_id: number
  transaction_reason_id: number | null
  transaction_type_id: number
  updated_by: number | null
  updatedAt: Date
  vaccine_sequence: number | null
  vendor_id: number | null
}

export interface TransactionTypes {
  chg_type: Generated<number>
  createdAt: Date
  deletedAt: Date | null
  id: Generated<number>
  title: string | null
  title_en: string | null
  updatedAt: Date
}

export interface UpdateStocks {
  createdAt: Date
  date_cutoff: Date
  deletedAt: Date | null
  id: Generated<number>
  master_material_id: number | null
  province_id: number | null
  qty: number
  regency_id: number | null
  stocks: string | null
  updatedAt: Date | null
}

export interface UserChgHistories {
  created_at: Date
  id: Generated<number>
  new_values: string
  old_values: string | null
  updated_at: Date
  updated_by: string
  user_id: number
}

export interface Users {
  address: string | null
  application_version: string | null
  change_password: Generated<number | null>
  created_at: Generated<Date>
  created_by: number | null
  daily_recap_email: Generated<number | null>
  date_of_birth: Date | null
  deleted_at: Date | null
  deleted_by: number | null
  email: string | null
  entity_id: number | null
  fcm_token: string | null
  firstname: string | null
  gender: number | null
  id: Generated<number>
  imei_number: string | null
  iota_app_gui_theme: string | null
  last_device: number | null
  last_login: Date | null
  last_mobile_access: Date | null
  lastname: string | null
  manufacture_id: number | null
  mobile_phone: string | null
  mobile_phone_2: string | null
  mobile_phone_brand: string | null
  mobile_phone_model: string | null
  password: string | null
  permission: string | null
  role: number | null
  sim_id: string | null
  sim_provider: string | null
  status: Generated<number | null>
  timezone_id: number | null
  token_login: string | null
  updated_at: Generated<Date>
  updated_by: number | null
  username: string | null
  view_only: Generated<number>
  village_id: string | null
}

export interface UsersCopy {
  address: string | null
  application_version: string | null
  change_password: Generated<number | null>
  created_at: Date
  created_by: number | null
  date_of_birth: Date | null
  deleted_at: Date | null
  deleted_by: number | null
  email: string | null
  entity_id: number | null
  fcm_token: string | null
  firstname: string | null
  gender: number | null
  id: Generated<number>
  imei_number: string | null
  iota_app_gui_theme: string | null
  last_device: number | null
  last_login: Date | null
  last_mobile_access: Date | null
  lastname: string | null
  manufacture_id: number | null
  mobile_phone: string | null
  mobile_phone_2: string | null
  mobile_phone_brand: string | null
  mobile_phone_model: string | null
  password: string | null
  permission: string | null
  role: number | null
  sim_id: string | null
  sim_provider: string | null
  status: Generated<number | null>
  timezone_id: number | null
  token_login: string | null
  updated_at: Date
  updated_by: number | null
  username: string | null
  view_only: Generated<number>
  village_id: string | null
}

export interface UserTags {
  created_at: Date
  deleted_at: Date | null
  id: Generated<number>
  title: string | null
  updated_at: Date
}

export interface UserUserTags {
  created_at: Date
  id: Generated<number>
  updated_at: Date
  user_id: number | null
  user_tag_id: number | null
}

export interface Villages {
  created_at: Date
  deleted_at: Date | null
  id: string
  name: string | null
  sub_district_id: string | null
  sub_district_id_new: string | null
  sub_district_id_old: string | null
  updated_at: Date
  village_id_new: string | null
  village_id_old: string | null
}

export interface VillagesBackup20240108 {
  created_at: Date
  deleted_at: Date | null
  id: string
  name: string | null
  sub_district_id: string | null
  updated_at: Date
}

export interface YearlyChild {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_id: number
  id: Generated<number>
  updated_at: Date
  updated_by: number | null
  yearly_plan_id: number | null
}

export interface YearlyChildHasIpvs {
  created_at: Date
  created_by: number | null
  custom_ipv: Generated<Decimal>
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  master_ipv_id: number
  status: string | null
  updated_at: Date
  updated_by: number | null
  yearly_child_id: number
}

export interface YearlyChildHasResults {
  activity_id: number | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  ipv: Generated<Decimal>
  master_material_id: number | null
  material_id: number | null
  monthly_distribution: Generated<string>
  monthly_need: number | null
  monthly_vial: number | null
  updated_at: Date
  updated_by: number | null
  version: Generated<number>
  weekly_need: number | null
  weekly_vial: number | null
  yearly_child_id: number
  yearly_need: Generated<number>
  yearly_vial: number | null
}

export interface YearlyChildHasTarget {
  created_at: Date
  custom_qty: Generated<number>
  deleted_at: Date | null
  id: Generated<number>
  master_target_id: number
  propotion: Generated<Decimal>
  qty: Generated<number>
  status: string | null
  updated_at: Date
  yearly_child_id: number
}

export interface YearlyParent {
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  province_id: number
  regency_id: number
  updated_at: Date
  updated_by: number | null
  year: string
}

export interface YearlyParentHasTarget {
  created_at: Date
  custom_qty: number | null
  deleted_at: Date | null
  id: Generated<number>
  master_target_id: number
  propotion: Generated<Decimal>
  qty: number | null
  status: string | null
  updated_at: Date
  yearly_plan_id: number | null
}

export interface YearlyPlanHasIpvs {
  created_at: Date
  created_by: number | null
  custom_ipv: Generated<Decimal>
  deleted_at: Date | null
  deleted_by: number | null
  id: Generated<number>
  master_ipv_id: number
  status: string | null
  updated_at: Date
  updated_by: number | null
  yearly_plan_id: number
}

export interface YearlyPlans {
  comment: string | null
  created_at: Date
  created_by: number | null
  deleted_at: Date | null
  deleted_by: number | null
  entity_regency_id: number
  id: Generated<number>
  status: string | null
  step: Generated<number>
  submitted_at: Date | null
  submitted_by: number | null
  updated_at: Date
  updated_by: number | null
  year: string
}

export interface MigrationDB {
  asset_models: AssetModels
  asset_types: AssetTypes
  assets: Assets
  batches: Batches
  biofarma_orders: BiofarmaOrders
  biofarma_smdv_orders: BiofarmaSmdvOrders
  coldchain_capacity_equipment_unused: ColdchainCapacityEquipmentUnused
  coldstorage_annual_planning: ColdstorageAnnualPlanning
  coldstorage_annual_planning_temperature: ColdstorageAnnualPlanningTemperature
  coldstorage_materials: ColdstorageMaterials
  coldstorage_per_temperature: ColdstoragePerTemperature
  coldstorage_transaction_logs: ColdstorageTransactionLogs
  coldstorages: Coldstorages
  commitment_items: CommitmentItems
  commitments: Commitments
  configurations: Configurations
  contracts: Contracts
  customer_vendors: CustomerVendors
  customer_vendors_290824: CustomerVendors290824
  dashboard_satusehat: DashboardSatusehat
  din_order_items: DinOrderItems
  din_orders: DinOrders
  download_logs: DownloadLogs
  educations: Educations
  entities: Entities
  entity_activity_date: EntityActivityDate
  entity_entity_tags: EntityEntityTags
  entity_has_master_materials: EntityHasMasterMaterials
  entity_master_material_activities: EntityMasterMaterialActivities
  entity_master_material_activities_03102022: EntityMasterMaterialActivities03102022
  entity_master_material_minmax: EntityMasterMaterialMinmax
  entity_prep_min_max: EntityPrepMinMax
  entity_tags: EntityTags
  entity_tags_old: EntityTagsOld
  ethnics: Ethnics
  event_report_child_reasons: EventReportChildReasons
  event_report_comments: EventReportComments
  event_report_histories: EventReportHistories
  event_report_items: EventReportItems
  event_report_reasons: EventReportReasons
  event_reports: EventReports
  extermination_flow_reasons: ExterminationFlowReasons
  extermination_flows: ExterminationFlows
  extermination_transaction_types: ExterminationTransactionTypes
  extermination_transactions: ExterminationTransactions
  integration_asik_aggregate: IntegrationAsikAggregate
  integration_ayo_sehat: IntegrationAyoSehat
  integration_order_items: IntegrationOrderItems
  integration_order_items_kfa: IntegrationOrderItemsKfa
  integration_order_logs: IntegrationOrderLogs
  integration_orders: IntegrationOrders
  kfa_levels: KfaLevels
  login_attempts: LoginAttempts
  manufactures: Manufactures
  mapping_cancel_discard: MappingCancelDiscard
  mapping_entities: MappingEntities
  mapping_master_materials: MappingMasterMaterials
  mapping_master_materials_030924: MappingMasterMaterials030924
  master_activities: MasterActivities
  master_ipvs: MasterIpvs
  master_kode_wilayah: MasterKodeWilayah
  master_material_has_activities: MasterMaterialHasActivities
  master_material_has_companions: MasterMaterialHasCompanions
  master_material_has_conditions: MasterMaterialHasConditions
  master_material_has_manufactures: MasterMaterialHasManufactures
  master_material_type: MasterMaterialType
  master_materials: MasterMaterials
  master_materials_copy: MasterMaterialsCopy
  master_target: MasterTarget
  master_target_distributions: MasterTargetDistributions
  master_target_regencies: MasterTargetRegencies
  master_volume_material_manufactures: MasterVolumeMaterialManufactures
  material_categories: MaterialCategories
  material_companions: MaterialCompanions
  material_conditions: MaterialConditions
  material_entity: MaterialEntity
  material_manufacture: MaterialManufacture
  material_material_categories: MaterialMaterialCategories
  material_material_tag: MaterialMaterialTag
  material_tags: MaterialTags
  materials: Materials
  new_opname_items: NewOpnameItems
  new_opname_stocks: NewOpnameStocks
  new_opnames: NewOpnames
  notification_types: NotificationTypes
  occupations: Occupations
  opname_actions: OpnameActions
  opname_item_reason_actions: OpnameItemReasonActions
  opname_period: OpnamePeriod
  opname_reasons: OpnameReasons
  opname_stock_items: OpnameStockItems
  opname_stocks: OpnameStocks
  order_comments: OrderComments
  order_histories: OrderHistories
  order_item_projection_capacities: OrderItemProjectionCapacities
  order_items: OrderItems
  order_items_kfa: OrderItemsKfa
  order_order_tag: OrderOrderTag
  order_reports: OrderReports
  order_stock_exterminations: OrderStockExterminations
  order_stock_purchase: OrderStockPurchase
  order_stocks: OrderStocks
  order_tags: OrderTags
  orders: Orders
  patients: Patients
  pieces_purchase: PiecesPurchase
  provinces: Provinces
  rabies_vaccine_rules: RabiesVaccineRules
  range_temperature: RangeTemperature
  reactions: Reactions
  reconciliation: Reconciliation
  reconciliation_item_reason_actions: ReconciliationItemReasonActions
  reconciliation_items: ReconciliationItems
  regencies: Regencies
  regencies_backup_2024_01_08: RegenciesBackup20240108
  regions: Regions
  religions: Religions
  request_order_items: RequestOrderItems
  request_orders: RequestOrders
  reset_passwords: ResetPasswords
  SequelizeMeta: SequelizeMeta
  service_types: ServiceTypes
  source_materials: SourceMaterials
  stock_activity_migration_logs: StockActivityMigrationLogs
  stock_exterminations: StockExterminations
  stock_intervals: StockIntervals
  stocks: Stocks
  stop_notification_histories: StopNotificationHistories
  stop_notification_reasons: StopNotificationReasons
  sub_districts: SubDistricts
  sub_districts_backup_2024_01_08: SubDistrictsBackup20240108
  timezones: Timezones
  track_devices: TrackDevices
  tracking_log_eg: TrackingLogEg
  transaction_injections: TransactionInjections
  transaction_items: TransactionItems
  transaction_patient_reactions: TransactionPatientReactions
  transaction_patients: TransactionPatients
  transaction_purchase: TransactionPurchase
  transaction_reasons: TransactionReasons
  transaction_types: TransactionTypes
  transactions: Transactions
  transactions_copy_220623: TransactionsCopy220623
  transactions_last_3months: TransactionsLast3months
  update_stocks: UpdateStocks
  user_chg_histories: UserChgHistories
  user_tags: UserTags
  user_user_tags: UserUserTags
  users: Users
  users_copy: UsersCopy
  villages: Villages
  villages_backup_2024_01_08: VillagesBackup20240108
  yearly_child: YearlyChild
  yearly_child_has_ipvs: YearlyChildHasIpvs
  yearly_child_has_results: YearlyChildHasResults
  yearly_child_has_target: YearlyChildHasTarget
  yearly_parent: YearlyParent
  yearly_parent_has_target: YearlyParentHasTarget
  yearly_plan_has_ipvs: YearlyPlanHasIpvs
  yearly_plans: YearlyPlans
}
